### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by oliveres** [Supergiovane/node-red-contrib-hikvision-ultimate#1]
Hi, I have repeating messages in daemon.log but everything is working. I'm scared about the SD card full of logs.

Dec 12 13:40:31 nodered Node-RED[329]: 12 Dec 13:40:31 - [info] **Hikvision-config**: DecodingBody: Invalid Json
Dec 12 13:40:31 nodered Node-RED[329]: Content-Type: application/xml; charset="UTF-8"
Dec 12 13:40:31 nodered Node-RED[329]: Content-Length: 845
Dec 12 13:40:31 nodered Node-RED[329]: #015

**Comment by Supergiovane** [comment]
Hi. Do you like my node? We italians do love when someone tells us “hi, great node”. 
Yes, this is a debug log that will be disabled today. 
Stay tuned with the update, star my kode if you like it and don’t forget do Like my facebook page, to stay up to date with news. 
https://m.facebook.com/supergiovaneDev/

**Comment by GeorgWolter** [comment]
hi, great node 👍👏

**Comment by oliveres** [comment]
Great node, the only one that works! Thank you.
