### ISSUE TITLE
connect to DVR error

### ISSUE THREAD

**Issue by ozett** [Supergiovane/node-red-contrib-hikvision-ultimate#10]
hi, good to see another hikvision module for node-red.
but i got errors when connecting to my dvr.
i can login on the weg-gui with the given credentials, but not with your node.
![image](https://user-images.githubusercontent.com/5937811/113561717-56c9ca00-9605-11eb-9ad3-aab96d9eba79.png)

node.js: v12.22.0
node.red: v1.2.9
Model: DS-7616NI-I2
Firmware: V4.22.005 build 191208

any hints?

https also shows error with self-signed dvr-certificate.
![image](https://user-images.githubusercontent.com/5937811/113561971-a8725480-9605-11eb-90b3-ba2145124da6.png)

**Comment by ozett** [comment]
i found newer firmware .22 -> .50 and will try this...

![image](https://user-images.githubusercontent.com/5937811/113562446-64338400-9606-11eb-8b4f-99481c606be1.png)

**Comment by ozett** [comment]
WOW. Updated seems to help...
![image](https://user-images.githubusercontent.com/5937811/113563014-503c5200-9607-11eb-98a6-a694eee52b22.png)

**Comment by Supergiovane** [comment]
Ok, let me know if you have other issues but please keep always all up to date, because with HTTPS you need to have the latest versions. Switching to HTTP should solve all your issues, even with old firmwares.

**Comment by ozett** [comment]
thanks for quick reply. 
but http and basic-auth with old firmware caused error.
maybe url-path changed from firmware ver.22 to v.55 in DVR.
as it was also a breaking change in the past on some cameras. 

glad i got it running, i will now see how it does stbilty-wise over time...
thanks for your work..

![image](https://user-images.githubusercontent.com/5937811/113564893-67307380-960a-11eb-859b-6e1f985f7975.png)

**Comment by Supergiovane** [comment]
Thank you for using one of my node.
I use it h24 even for my Hikvision Radars and it runs rock solid.
I you like it, please click the "star" button above on gitHub's menu. Thanks.
