### ISSUE TITLE
add example for picture node

### ISSUE THREAD

**Issue by ozett** [Supergiovane/node-red-contrib-hikvision-ultimate#11]
maybe an interesting [another way](https://flows.nodered.org/node/node-red-contrib-image-output) to show images directly in node-red?
worth to show another way for the [picture-node on readme.md](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate#picture-node)?

![image](https://user-images.githubusercontent.com/5937811/113567166-613c9180-960e-11eb-95d8-ce63937e758b.png)

**Comment by Supergiovane** [comment]
Very interesting. I’ll take a look!

**Comment by ozett** [comment]
Great. 
my use of the images from motion-detection is to let a python-script run over it and see with AI for detection.
even if there are false-positives, its way better than simple motion.

i do it on an virtual ubuntu 20.04lts host with openCV 4.4 installed. that brings you YOLO4 for AI-Detection out of the box.
Install is not that complicated. at the end you have to push images to the script (from node-red).
runs for over a year now very sussesful.

![image](https://user-images.githubusercontent.com/5937811/113568288-8d591200-9610-11eb-8e53-a9638982b314.png)

**Comment by Supergiovane** [comment]
The link to the node you mentioned will be out today with version 1.0.34.
Thank you for your suggestion.
