### ISSUE TITLE
HIKVision NVR POE

### ISSUE THREAD

**Issue by vvfrwl** [Supergiovane/node-red-contrib-hikvision-ultimate#12]
Hi,
Is it possible to manage NVR POE settings from node-red \ HIK SDK?
For example NVR DS-7608NI-I2.
It needs to switch off several cameras if you at home \ switch on if away.
![image](https://user-images.githubusercontent.com/59322588/113638737-3f7bf280-9680-11eb-8d56-7ca895c3ed4f.png)

Good work, Thank you,

**Comment by Supergiovane** [comment]
Hi,
i'm currently busy on opdating another my node, so i cannot touch this at this time.
You can use the **hikvisionUltimateXML** node to accomplish your needs, by passing the XML string to control POE ports (but i'm not sure if you can control POE ports from APIs). You need the hikvision API documentation as well.

**Comment by Supergiovane** [comment]
Hi
i searched on all PDF files of ISAPI i found on internet, but none tells how to toggle POE power.
If you ever find one, please point me on that!
