### ISSUE TITLE
IP cameras still not working

### ISSUE THREAD

**Issue by smcgann99** [Supergiovane/node-red-contrib-hikvision-ultimate#13]
Hi,

Just tried this with my HVR analog cams 1 to 3 work as expected but IP cams give me bad request, any ideas ?

**Comment by Supergiovane** [comment]
Hi
Sorry, you need to be more specific.
What type/model of NVR do you have?
What hikvision node you're using?
Have you tried to update the NVR firmware?
Thanks.

**Comment by smcgann99** [comment]
dvr is 8 channel hybrid 
Model: iDS-7208HUHI-K1/4S(B)
Firmware: V4.26.010

raw alarm node works and shows for example 

dynChannelID: "12"
dateTime: "2021-04-06T10:42:4300:00"
activePostCount: "2"
eventType: "linedetection"
eventState: "active"
eventDescription: "linedetection alarm"

but picture node for ip camera(12) gives bad request message on node status, analog cameras do work as expected

**Comment by Supergiovane** [comment]
Hi,
hybrid NVR have been always problematic.
Please, you should add "banana" after the NVR IP in the config window. 
This will activate the debug log in node-red. You should restart node-red and retry to get an image, then send me the log in some way (screenshot or text file).
For example, if your NVR's IP is 192.168.1.22, you should write **192.168.1.22banana** in the config window.

**Comment by smcgann99** [comment]
"Hikvision-config: clientGenericRequest.fetch error Error response: Bad Request"

**Comment by Supergiovane** [comment]
Hmm.. the url is different but i’ve no documentation about the url of your nvr

**Comment by smcgann99** [comment]
it is spamming the log with 2 messages - 
BANANA PROCESSING

Content-Type: application/xml; charset="UTF-8"

Content-Length: 467



<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>ac:cb:51:e7:ed:ca</macAddress>
<channelID>0</channelID>
<dateTime>2021-04-06T17:56:0500:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>

**Comment by smcgann99** [comment]
<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>ac:cb:51:e7:ed:ca</macAddress>
<channelID>0</channelID>
<dateTime>2021-04-06T17:48:2800:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
6 Apr 17:48:29 - [error] BANANA SBANANATO XML -> JSON {"EventNotificationAlert":{"$":{"version":"1.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"192.168.1.81","portNo":"80","protocol":"HTTP","macAddress":"ac:cb:51:e7:ed:ca","channelID":"0","dateTime":"2021-04-06T17:48:2800:00","activePostCount":"0","eventType":"videoloss","eventState":"inactive","eventDescription":"videoloss alarm"}}
6 Apr 17:48:39 - [info] SPLITTATO RESULT COUNT: ####### 2 ###################### FINE SPLITTATO RESULT
6 Apr 17:48:39 - [info] SPLITTATO RESULT EMPTY: #######  ###################### FINE SPLITTATO RESULT
6 Apr 17:48:39 - [error] BANANA PROCESSING
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>ac:cb:51:e7:ed:ca</macAddress>
<channelID>0</channelID>
<dateTime>2021-04-06T17:48:3800:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
6 Apr 17:48:39 - [error] BANANA SBANANATO XML -> JSON {"EventNotificationAlert":{"$":{"version":"1.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"192.168.1.81","portNo":"80","protocol":"HTTP","macAddress":"ac:cb:51:e7:ed:ca","channelID":"0","dateTime":"2021-04-06T17:48:3800:00","activePostCount":"0","eventType":"videoloss","eventState":"inactive","eventDescription":"videoloss alarm"}}

**Comment by Supergiovane** [comment]
What version of node have you installed?
Please issue a node -v on a command prompt

**Comment by smcgann99** [comment]
v14.6.0

**Comment by Supergiovane** [comment]
The node version should be ok. 
You should leave the log running and request for an image. Then stop the log. 
I need to see the exact response from the nvr when you ask for an image.

**Comment by smcgann99** [comment]
6 Apr 18:04:20 - [info] Hikvision-config: before Pipelining...

6 Apr 18:04:29 - [info] SPLITTATO RESULT COUNT: ####### 2 ###################### FINE SPLITTATO RESULT
6 Apr 18:04:29 - [info] SPLITTATO RESULT EMPTY: #######  ###################### FINE SPLITTATO RESULT
6 Apr 18:04:29 - [error] BANANA PROCESSING
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

6 Apr 18:04:29 - [info] Hikvision-config: DecodingBody Info only: Invalid Json
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

6 Apr 18:04:38 - [info] SPLITTATO RESULT COUNT: ####### 2 ###################### FINE SPLITTATO RESULT
6 Apr 18:04:38 - [error] BANANA PROCESSING<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>ac:cb:51:e7:ed:ca</macAddress>
<channelID>0</channelID>
<dateTime>2021-04-06T18:04:2800:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
6 Apr 18:04:38 - [error] BANANA SBANANATO XML -> JSON {"EventNotificationAlert":{"$":{"version":"1.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"192.168.1.81","portNo":"80","protocol":"HTTP","macAddress":"ac:cb:51:e7:ed:ca","channelID":"0","dateTime":"2021-04-06T18:04:2800:00","activePostCount":"0","eventType":"videoloss","eventState":"inactive","eventDescription":"videoloss alarm"}}
6 Apr 18:04:38 - [error] BANANA PROCESSING
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>ac:cb:51:e7:ed:ca</macAddress>
<channelID>0</channelID>
<dateTime>2021-04-06T18:04:3700:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>videoloss</eventType>
<eventState>inactive</eventState>
<eventDescription>videoloss alarm</eventDescription>
</EventNotificationAlert>
6 Apr 18:04:38 - [error] BANANA SBANANATO XML -> JSON {"EventNotificationAlert":{"$":{"version":"1.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"192.168.1.81","portNo":"80","protocol":"HTTP","macAddress":"ac:cb:51:e7:ed:ca","channelID":"0","dateTime":"2021-04-06T18:04:3700:00","activePostCount":"0","eventType":"videoloss","eventState":"inactive","eventDescription":"videoloss alarm"}}
6 Apr 18:04:42 - [error] Hikvision-config: clientGenericRequest.fetch error Error response: Bad Request
6 Apr 18:04:47 - [info] SPLITTATO RESULT COUNT: ####### 2 ###################### FINE SPLITTATO RESULT
6 Apr 18:04:47 - [info] SPLITTATO RESULT EMPTY: #######  ###################### FINE SPLITTATO RESULT
6 Apr 18:04:47 - [error] BANANA PROCESSING
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

**Comment by smcgann99** [comment]
FYI 

/ISAPI/ContentMgmt/StreamingProxy/channels/1201/picture = ip camera 12
/ISAPI/Streaming/channels/101/picture = analog camera 1 
perhaps you can add an option in the node to select method ?

**Comment by Supergiovane** [comment]
Hmmm interesting...
But does it work? Have you tried to get the image from a web browser, passing the /ISAPI/ContentMgmt/StreamingProxy/channels/1201/picture string?

**Comment by Supergiovane** [comment]
V. 1.0.34 will be out today with the fix.
Thank you for you help in finding the string.
If it doesn't work, please reopen this issue.
Cheers.

**Comment by smcgann99** [comment]
I see the yellow status only for frist trigger, but no picture is returned, after that another trigger doesn't produce any debug output or status message, also no picture. 
8 Apr 00:19:07 - [info] BANANA IT DOES NOT WORK GETTING IMAGE WITH WITH
8 Apr 00:19:07 - [info] BANANA TRYING GETTING IMAGE WITH
8 Apr 00:19:10 - [info] SPLITTATO RESULT COUNT: ####### 2 ###################### FINE SPLITTATO RESULT
8 Apr 00:19:10 - [error] BANANA PROCESSING<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>192.168.1.81</ipAddress>

**Comment by Supergiovane** [comment]
Hi
Have you tried to get the image from a web browser, passing the /ISAPI/ContentMgmt/StreamingProxy/channels/1201/picture string?

**Comment by Supergiovane** [comment]
Also, please unzip this zip into yout **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder and restart node red. Then try again.

[hikvisionUltimatePicture.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6276151/hikvisionUltimatePicture.js.zip)

**Comment by Supergiovane** [comment]
Hello scm
can you give me a feedback about this issue?

**Comment by smcgann99** [comment]
/ISAPI/ContentMgmt/StreamingProxy/channels/1201/picture 
I already use this path with standard http request node and it works OK.

tried your new code - ip cameras still not working. yellow node status message is not displaying anymore.  

10 Apr 09:43:37 - [info] Hikvision-config: DecodingBody Info only: Invalid Json
Content-Type: application/xml; charset="UTF-8"
Content-Length: 467

10 Apr 09:47:03 - [error] Hikvision-config: clientGenericRequest.fetch error Error response: Service Unavailable

**Comment by Supergiovane** [comment]
Hmmm. So the querystring you proposed is invalid. 
Do you have other to test?

**Comment by smcgann99** [comment]
no the string is correct I am already using it in node red

**Comment by smcgann99** [comment]
I don't see your node status messages so I don't think that that code is working

**Comment by Supergiovane** [comment]
Hmm... maybe a syntax error.... 
Let me check.

**Comment by Supergiovane** [comment]
Have you installed the latest version?

**Comment by smcgann99** [comment]
admin:*****@192.168.1.81/ISAPI/ContentMgmt/StreamingProxy/channels/901/picture I have this in http request nodes at the moment to capture images.....

**Comment by smcgann99** [comment]
I copied the zip file yes

**Comment by Supergiovane** [comment]
You're using basic authentication. 
Have you tried to set the basic authentication in the config window ?

**Comment by Supergiovane** [comment]
The latest version is 1.0.37.
Please install it.

**Comment by smcgann99** [comment]
after deploy first time I click inject node I see yellow status on picture node but no output. Second click no status and no output

**Comment by smcgann99** [comment]
dont think authentication is an issue as analog channels work with either option

**Comment by Supergiovane** [comment]
Are you on v. 1.0.37?

**Comment by smcgann99** [comment]
yes

**Comment by smcgann99** [comment]
rather than trying all paths perhaps you could have a drop down in picture node to select it ?

**Comment by Supergiovane** [comment]
Yes, but trying paths is more simple for end user.
Can you please unzip this and try again?
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6289571/knxUltimate-config.js.zip)

**Comment by smcgann99** [comment]
think this is wrong file ?

**Comment by Supergiovane** [comment]
Hi
this is the correct one, put it here **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes**
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6289579/knxUltimate-config.js.zip)
It should work.

**Comment by Supergiovane** [comment]
Anyway, the error you received (service unavaiable) means that at the moment, the webserver of the camera is unable to fulfill the request. If you've many things connected to the camera, you may run out of connection limit.

**Comment by smcgann99** [comment]
I have copied but that file didn't exist before ?
restarted node red but still only see yellow warning on first click and nothing after that. 
It doesn't look like the code works after the first path fails, never see the red warning etc...
Have to go now but if you find anything post it and I will try it later

**Comment by Supergiovane** [comment]
Yes it was existing.
Maybe you're copying it to the wrong place?

**Comment by Supergiovane** [comment]
You should see all these files it the directory:

<img width="524" alt="nodes" src="https://user-images.githubusercontent.com/37666636/114265492-5bb9bf80-99f1-11eb-9a98-959d4c2b9ea6.png">

**Comment by smcgann99** [comment]
knxUltimate-config.js was not in the directory and it is not in your screen shot above, hence I thought you sent the wrong file ?

**Comment by Supergiovane** [comment]
Holy crap!!
Sorry!
THIS is the right file!! SORRY!!!!
[Hikvision-config.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6289603/Hikvision-config.js.zip)

**Comment by smcgann99** [comment]
as above -
restarted node red but still only see yellow warning on first click and nothing after that.
It doesn't look like the code works after the first path fails, as I never see the red warning etc...
Have to go now but if you find anything post it and I will try it later

**Comment by Supergiovane** [comment]
Ok, see you later.
As soon as you return, please try this file. The first URL is ISAPI/ContentMgmt/StreamingProxy/channels/....

[hikvisionUltimatePicture.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6289614/hikvisionUltimatePicture.js.zip)

**Comment by Supergiovane** [comment]
PS: please remove **BANANA** from the IP, otherwise it will never work.

**Comment by Supergiovane** [comment]
Hi SMC
wellcome back.
There was a stupid syntax error during a URL check.
Please unzip these files and retry. Now it should be OK

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6289667/Archivio.zip)

**Comment by smcgann99** [comment]
For analog camera I got yellow warning followed by the picture, so it did use 2nd url OK. 
As a test I set analog to an unused channel, which did then show the red warning on node status.
with IP cam I do not get a picture or any status message, there is no output from picture node on either output.

**Comment by Supergiovane** [comment]
Use two different nodes, one for each type of cam. 
After finding the right url, it is be retained by the node, so when you switch to a cam using the other url, it doesn’t work anymore. 
Or restart nodered to reset the retained url.

**Comment by smcgann99** [comment]
yes, I have 2 nodes setup, also deleted and re-added them but do not get anything from ip cameras

**Comment by smcgann99** [comment]
I just noticed that ALL the picture nodes status  is showing “picture received” every time I get an alarm on my dvr, the output is just undefined.

**Comment by Supergiovane** [comment]
> I just noticed that ALL the picture nodes status is showing “picture received” every time I get an alarm on my dvr, the output is just undefined.

Does this happens prior to these new changes in the nodes?

**Comment by smcgann99** [comment]
not sure didn't notice

**Comment by Supergiovane** [comment]
OK,
anyway. I need time to do a good job. The goal is to store the valid URL on a file, to avoid to loop through URLs at every node-red restart.
To make it ever worse, i cannot try this at home because i don't own an hybrid NVR, so i proceed walking on the blind fog.

In the meantime, unzip these files.
Every time you enter the config window, it tries to loop through URLs to find the right one. Open the config window, select your channel and wait until you see a picture.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6290343/Archivio.zip)

**Comment by Supergiovane** [comment]
I'll give it a shot on Monday, as soon as i arrive at office, but the last zip should at least work.
If not, you can rollback by installing an old version. 
The latest "stable" one is 
npm install node-red-contrib-hikvision-ultimate@1.0.33

**Comment by Supergiovane** [comment]
PS: where you bought your nvr? Maybe i can try to buy one for testimg pourposes.

**Comment by smcgann99** [comment]
its a - iDS-7208HUHI-K1/4S(B)

**Comment by Supergiovane** [comment]
Does it wirk with the latest zip?

**Comment by smcgann99** [comment]
looking good so far

**Comment by smcgann99** [comment]
still getting undefined payloads on all picture nodes when dvr gets an alarm, but ip cams now work

**Comment by smcgann99** [comment]
not sure why picture nodes are triggered by dvr, looks like your heart beat is listening to wrong messages ?

I know it may not be so easy with the node as it works now, but it would be really good if it could display channel sent as a payload ;-)

**Comment by Supergiovane** [comment]
Do you need a property in the msg output telling you from wich channel is coming the picture? I’ve correctly understood?

**Comment by Supergiovane** [comment]
Hi smc,
for the channel ID in the payload, you can use the node.topic property.
V. 1.0.40 should have been fixed the issue with URL and with the false node status/payload indication.
You need to enter the config window of the picture node and clich "regresh image" to get the image.
Let me know.

Thanks.

**Comment by smcgann99** [comment]
installed latest files but I cannot get any pictures now just the following error -

TypeError: Cannot read property 'toString' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes/hikvisionUltimatePicture.js:89:64
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /usr/local/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:75:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)

**Comment by Supergiovane** [comment]
Have you installed the version 1.0.40 ?

**Comment by smcgann99** [comment]
yes

**Comment by Supergiovane** [comment]
Hi, 
i tested several times and i cannot reproduce the issue.
At the line you mentioned, it never occurs that these error is raised. This is a very simple string manipulation. I suspect that the hikvisionUltimatePicture.html file is old and it has not been updated.
I attached you some files coming from 1.0.40 to unzip in the usual folder.
Please try that.
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6301455/Archivio.zip)
If unsuccessfull, i need to view your nodes. Please paste here your node's code by exporting the JSON via "Export" menu in node-red.
Thanks

**Comment by Supergiovane** [comment]
Hi, 
please upgrade to 1.0.41. 
If the URL's array index exceeded the array lenght, an issue similar to "toString" can happen.

Let me know.

**Comment by smcgann99** [comment]
latest fix seems to be working now, will have a play with other nodes now ;-)
