### ISSUE TITLE
server port

### ISSUE THREAD

**Issue by Mateiuc** [Supergiovane/node-red-contrib-hikvision-ultimate#14]
Hi, my ip camera has different port than 80...the server node use always port 80, even if i change it. I got this error with debug : " Fetch error request to http://192.168.xxx.xxx/ISAPI/Event/notification/alertStream failed, reason: connect ECONNREFUSED 192.168.xxx.xxx:80 ", my port is 81..
Thanks

**Comment by Supergiovane** [comment]
Hi Mateuic
have you starred my node? Remember to do it :-)
Today a new version with that fix will be out. I'll advise you when ready.

**Comment by Supergiovane** [comment]
V. 1.0.42 is out for the fix.
Thank you for check it out and let me know if it still not working,.
