### ISSUE TITLE
Problem with ANPR 

### ISSUE THREAD

**Issue by river20081997** [Supergiovane/node-red-contrib-hikvision-ultimate#15]
Help me.
I can't connect to my ANPR camera HIKVISION via this module.
I add new ANPR node, configure IP, username, password, auth protocol but it isn't have effect.  
Maybe do I first need prepare my camera ?

**Comment by Supergiovane** [comment]
What error you get?
Have you clicked “connect” on the config window?

**Comment by river20081997** [comment]
My get error
![image](https://user-images.githubusercontent.com/83035963/115879239-1ade9380-a452-11eb-896c-8704d28152f9.png)

Yes, tried. But click was finished with error
![image](https://user-images.githubusercontent.com/83035963/115879538-70b33b80-a452-11eb-9b01-e0f7ec67b55e.png)

**Comment by Supergiovane** [comment]
Have you followed the indication to save and deploy first?
If yes, please check the credentials. "Forbidden" means that the credentials are either wrong or that you heven't enabled the API on the camera. Please check that as well.

**Comment by river20081997** [comment]
Yes. I deployed before click "connect"
API on camera is Enabled and username/password is right

**Comment by Supergiovane** [comment]
Hi
What model do you have?
Please tell me the node version and nodered version as well. 
For node, issue a node -v command
Thanks.

**Comment by river20081997** [comment]
CAMERA - iDS-2CD7A26G0/P-IZHS
V5.5.130 build 200820 Firmware version of Camera

NODE - v12.22.1
NODE-RED - v1.3.2

**Comment by Supergiovane** [comment]
It should be ok. 
Do you use digest or basic authentication? Have uou tried to switch from digest to basic and vice versa?
What querystring do you use with postman?

**Comment by Supergiovane** [comment]
PS: try also to use, for example, the picture node and let me know!

**Comment by river20081997** [comment]
> PS: try also to use, for example, the picture node and let me know!

Node picture connect successfully to this camera
![image](https://user-images.githubusercontent.com/83035963/115914959-4de94d00-a47b-11eb-96b8-5e7fa4f9cdc2.png)

**Comment by Supergiovane** [comment]
What querystring do you use with postman?

**Comment by river20081997** [comment]
> basic

I use digest authentication
Yes, but this switch in setting don't work correctly. I cound't  select basic auth (this parametr cann't be saved). 
I don't know specific querystring by this problem. I checked auth proccess in postman.

**Comment by Supergiovane** [comment]
Tomorrow i’ll take a look at that. 
I use the ANPR node succesfully everyday with my ip camera and works great. 
There should be something wrong in the digest/basic selection option.

**Comment by Supergiovane** [comment]
Hello
V. 1.0.43 is out with a fix with all issues you have.
Thank you for reporting that!

**Comment by river20081997** [comment]
Button 'connect' worked correctly now. But node can't work correctly.

**Comment by river20081997** [comment]
![image](https://user-images.githubusercontent.com/83035963/115954709-2043e880-a4fb-11eb-9ac8-0e5f55cf5f7c.png)

**Comment by river20081997** [comment]
![image](https://user-images.githubusercontent.com/83035963/115954731-423d6b00-a4fb-11eb-8944-86a5cf883d68.png)

**Comment by Supergiovane** [comment]
Ok, you can now try to switch from digest and basic and vice versa. 
On each switch, please restart node-red

**Comment by river20081997** [comment]
Yes. Now I can switch from digest and basic and vice versa.
But node return 
![image](https://user-images.githubusercontent.com/83035963/115956229-4de15f80-a504-11eb-8fa7-a000acdbf639.png)

**Comment by Supergiovane** [comment]
Hi
Have you maybe some IP filtering active on the camera? Is the admin user allowed to use the API?
Please put banana after the ip. For example 192.168.1.103banana

Restart nodered. From now onwards, node red starts logging a lot of things. I need this log to sort out something, because these infos are kot enough. Thanks.

**Comment by river20081997** [comment]
I'm found problem
![image](https://user-images.githubusercontent.com/83035963/115958296-905c6980-a50f-11eb-9871-8115b56e504e.png)

Do you have full api doc by this function?
Maybe  this function in firmware was changed?

**Comment by river20081997** [comment]
> Hi
> Have you maybe some IP filtering active on the camera? Is the admin user allowed to use the API?
> Please put banana after the ip. For example 192.168.1.103banana
> 
> Restart nodered. From now onwards, node red starts logging a lot of things. I need this log to sort out something, because these infos are kot enough. Thanks.

I'm not use IP filtering on the camera.
User admin allowedto use the API.

**Comment by Supergiovane** [comment]
[Hikvision ISAPI Core Protocol.pdf](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6369569/Hikvision.ISAPI.Core.Protocol.pdf)

Hi
This is very strange. Attached, API docs. 
This should be the only and valid api call to get the plates...

**Comment by jensfr1** [comment]
Hi, I am getting with 
DEVICE INFORMATION
Model: DT2A404
Firmware: V5.6.12
The taling picture just works fine. Maybe that camera is not supported? 

![image](https://user-images.githubusercontent.com/12272992/119099784-8b5bde80-ba17-11eb-9964-4621160f78a5.png)

**Comment by Supergiovane** [comment]
Hi jensfr1,
i don't understand your issue.
Also please open a new issue, do not reply to an opened and different one.
Thanks.

**Comment by Supergiovane** [comment]
Also... the DT2A404 is not an ANPR camera. Are you sure about the model?
