### ISSUE TITLE
Intrusion Detection

### ISSUE THREAD

**Issue by wizard3110** [Supergiovane/node-red-contrib-hikvision-ultimate#16]
Excellent set of nodes.

I have several cameras and have been trialling your alarm node with both the Hikvision DS-2CD2386G2-I and Annke C800 I91BF. Both cameras are setup in the same spot with the same settings and the same zones for motion/line crossing/intrusion.

Both cameras work well with video motion and line crossing, however with the intrusion detection the node doesn’t seem to send true when the event commences for the Hikvision DS-2CD2386G2-I (monitored via the IVMS Event Center). The Annke C800 I91BF sends true immediately then false after, however the Hikvision DS-2CD2386G2-I only sends false 5-10 seconds after event trigger. For line crossing the Hikvision DS-2CD2386G2-I sends true successfully then false soon after.

Below are screenshots from the Event Center showing 2 different triggers, and also the Node-Red debug node (connected direct to the alarm node [set to intrusion direction]) showing only the false.

![image](https://user-images.githubusercontent.com/83105946/115949286-9a2d9f00-a506-11eb-8944-24ea796cad4a.png)

![image](https://user-images.githubusercontent.com/83105946/115949291-9f8ae980-a506-11eb-8eed-cc2ac1c1a28e.png)

Would appreciate some assistance as the Annke C800 I91BF in the same scenario show 2 triggers in Event Center and also in Node-Red debug node.

![image](https://user-images.githubusercontent.com/83105946/115949295-a44f9d80-a506-11eb-9788-01e8b0a15b01.png)

![image](https://user-images.githubusercontent.com/83105946/115949298-a7e32480-a506-11eb-9662-5890b11313f4.png)

**Comment by Supergiovane** [comment]
HI wizard,
let me do some tests with my cameras.

**Comment by Supergiovane** [comment]
Hi Wizard
i checked with 2 my IP Cams and my PTZ and both sends TRUE and then FALSE at each intrusion detection.
Can you please do a screenshot of your alarm node config? Mine is set like this

<img width="494" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/115952953-452f6000-a4e9-11eb-8326-8cc895826058.png">

**Comment by Supergiovane** [comment]
PS: can you please use the RAW alarm node, attach a debug node to it and show me what it detects, whenever you enter the intrusion area of the HIKVISION camera? Thanks.

**Comment by wizard3110** [comment]
Hi Supergiovane,

**Config is as follows...**

![image](https://user-images.githubusercontent.com/83105946/115953429-0798fa00-a51e-11eb-8a84-b1e5ef2d2793.png)

**Several outputs from the Debug attached to the RAW Alarm...**

{"$":{"version":"2.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"10.0.0.2","ipv6Address":"::ffff:10.0.0.2","portNo":"80","protocol":"HTTP","macAddress":"08:a1:89:6a:3d:59","channelID":"1","dateTime":"2021-04-24T16:59:47+08:00","activePostCount":"1","eventType":"fielddetection","eventState":"active","eventDescription":"fielddetection alarm","DetectionRegionList":{"DetectionRegionEntry":{"regionID":"1","sensitivityLevel":"50","RegionCoordinatesList":{"RegionCoordinates":[{"positionX":"363","positionY":"872"},{"positionX":"653","positionY":"870"},{"positionX":"631","positionY":"666"},{"positionX":"418","positionY":"676"}]},"detectionTarget":"human","TargetRect":{"X":"508","Y":"705","width":"49","height":"198"}}},"channelName":"Hik","detectionPictureTransType":"binary","detectionPicturesNumber":"1","isDataRetransmission":"false"}

![image](https://user-images.githubusercontent.com/83105946/115953649-58f5b900-a51f-11eb-97c4-88c1e9602151.png)

**Then 5 of the following across 5 seconds...**

{"$":{"version":"2.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"10.0.0.2","ipv6Address":"::ffff:10.0.0.2","portNo":"80","protocol":"HTTP","macAddress":"08:a1:89:6a:3d:59","channelID":"1","dateTime":"2021-04-24T16:59:47+08:00","activePostCount":"1","eventType":"duration","eventState":"active","eventDescription":"duration alarm","channelName":"Hik","DurationList":{"Duration":{"relationEvent":"fielddetection"}},"isDataRetransmission":"false"}

![image](https://user-images.githubusercontent.com/83105946/115953693-86dafd80-a51f-11eb-8232-4ec07d6d460b.png)

**Then finally..**

{"$":{"version":"2.0","xmlns":"http://www.hikvision.com/ver20/XMLSchema"},"ipAddress":"10.0.0.2","ipv6Address":"::ffff:10.0.0.2","portNo":"80","protocol":"HTTP","macAddress":"08:a1:89:6a:3d:59","channelID":"1","dateTime":"2021-04-24T16:59:56+08:00","activePostCount":"1","eventType":"fielddetection","eventState":"inactive","eventDescription":"fielddetection alarm","channelName":"Hik"}

![image](https://user-images.githubusercontent.com/83105946/115953715-9fe3ae80-a51f-11eb-9744-320604204615.png)


Thanks.

**Comment by Supergiovane** [comment]
Thank you.
That's very useful.
Leave me check what's the difference between mine and you camera. Unfortunately, the Hik documentation over these APIs is very poorly written.

**Comment by Supergiovane** [comment]
Hi wizard
I saw you're smart, so can you please unzip the content of this zip, into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** and restart node-red?
As soon as you fires the intrusion alarm, a BANANA Log should appear in the node-red debug window and BANANA should appear in the node status.

[ciao.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6369352/ciao.zip)

**Comment by wizard3110** [comment]
Hi Supergiovane,

Below is the Event Center capturing 4 events...

![image](https://user-images.githubusercontent.com/83105946/115977166-03192380-a5a8-11eb-965c-7d614609d01c.png)

Below is the output from the Node-Red debug window per your instructions, for the same 4 events...

![image](https://user-images.githubusercontent.com/83105946/115977192-54291780-a5a8-11eb-93e9-497eef072390.png)

As you can see they are all false, and several seconds behind the actual alarm time.

Thanks for your help.

**Comment by Supergiovane** [comment]
Hi Wizard
by passing your alert string directly to the node, all works good and i obtain
`
{
  payload: true,
  topic: '',
  channelid: '1',
  zone: 1,
  description: 'fielddetection alarm'
}
`
As expected, the payload is true.
I really cannot find out the issue, but having multiple "false" payloads after some seconds from the triggering of the intrusion, leave me think about some issues with the node configuration itself.
Can you please delete the node (not the server one, only the alarm node), deploy and put again a new alarm node in the flow (please do not copy/paste the old one, just add a new one)?
Thanks.

**Comment by wizard3110** [comment]
Hi Supergiovane,

I've deleted the original node, and replaced with a new alarm node with the same server details and deployed, but unfortunately with the same result. I also tried a different Pi/Node-Red build I have loading the package and deploying an alarm node connected to the same camera, but again with the same result.

I certainly get payload true and then false for Line Crossing...

![image](https://user-images.githubusercontent.com/83105946/115984833-a46d9d00-a5db-11eb-8c5a-dd185e32e8c3.png)

...and also payload true and then false for Region Entrance (although a little delayed from the alarm event)...

![image](https://user-images.githubusercontent.com/83105946/115984997-53aa7400-a5dc-11eb-8efe-91413f0460ed.png)

...but still only false for Intrusion Detection.

![image](https://user-images.githubusercontent.com/83105946/115985176-3aee8e00-a5dd-11eb-92b5-7c8f4fe4267d.png)

**Comment by Supergiovane** [comment]
I need to ditch more into that tomorrow in office. 
For info, what you see from the RWA alarm output is what i get into the alarm node as well. 
In the alarm node i take this raw message and parse the eventtype to find the “fielddetection” string having eventstate “active”. This triggers the payload true. Eventstate “inactive” triggers the payload false. 
For some reasons, they don’t work.  
Injecting the string coming from your RAW alarm sample above, into the alarm node, does work. 
In the meantime i fix this thing, you can use the RAW alarm and filter for these properties to do what you want.

**Comment by wizard3110** [comment]
Hi Supergiovane,

Based on your last message and the explanation of how the alarm node details are extracted from the RAW alarm, I had a look in to the output coming from the RAW node. I assessed each of Motion Detection, Line Crossing and Intrusion Detection, with the intention of extracting the key details as you suggested.

There are some other useful properties also, but from what I can tell the key properties are eventType (for alarm type) and eventState (for active or inactive). This being the case, I compared the different alarms.

For Motion Detection, the eventType is VMD and eventState either active or inactive. Line Crossing is similar, with eventType linedetection and eventState either active or inactive. 

For Intrusion Detection though, when the alarm is triggered the eventType is duration and eventState is active, then when the alarm stops the eventType is fielddetection and eventState is inactive. Is the active output correct? If the intension for Intrusion Detection is the same as Motion Detection and Line Crossing, should the eventType be fielddetection instead of duration?  fielddetection is part of the overall output for active so would eventually be picked-up, but further down instead of eventType.

Below are some snips…

Line Crossing active then inactive

![image](https://user-images.githubusercontent.com/83105946/116036090-b5301880-a698-11eb-8022-64e605f81bb2.png) ![image](https://user-images.githubusercontent.com/83105946/116036103-b9f4cc80-a698-11eb-8998-9860ef9aed90.png)

Intrusion Detection active then inactive

![image](https://user-images.githubusercontent.com/83105946/116036130-c5e08e80-a698-11eb-96b8-effff7380d7e.png) ![image](https://user-images.githubusercontent.com/83105946/116036140-caa54280-a698-11eb-92c7-68d161a25704.png)

**Comment by Supergiovane** [comment]
Hi Wizard
Thank you for ditching into that.
Yes i noted that, but the "duration" event tells the receiver, that the subject is moving into the region.
If you look at your message here https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/issues/16#issuecomment-826062229 you note that the RAW node picks up the "fielddetection" "active" as well:

![115953649-58f5b900-a51f-11eb-97c4-88c1e9602151](https://user-images.githubusercontent.com/37666636/116038086-44bdd300-a669-11eb-8bc2-6f2d4e0d6714.png)

So there must be something wrong, because as far i can seen, sometime the event "fielddetection" is fired, sometime not.
For a pure and simple workaround, i can add pick up the "duration" event, to signal an intrusion detection, but the "duration" is common to other events as well and that's a problem.
The fact that your other camera do works everytime, leave me thinking something wrong with the Hikvision firmware.
Are you able to update the Hikvision camera firmware?

**Comment by wizard3110** [comment]
Yes you are right, there was "fielddetection" "active" previously on the Hikvision DS-2CD2386G2-I, and also on the Annke C800 I91BF.

I'll have a look at the firmware, and do a few more checks of the RAW Alarm between different cameras, and maybe different firmware on the Hikvision.

**Comment by Supergiovane** [comment]
Ok, let me know!

**Comment by Supergiovane** [comment]
This sort of alarm stream alerter should be nearly identical for the entire range of Hik cameras.
It's very useful to leave the RAW node attached and to monitor if at every intrusion detection, it emits a "fielddetection" "active". If yes, there is some issue somewhere else, otherwise, it can be an issue with the camera (please check that the maximum allowed connection to the camera hasn't been reached).

**Comment by Supergiovane** [comment]
Hi Wizard
Please install v. 1.0.44.
The fix for you issue has been done, with correct attribution of "duration" to "fielddetection".
If you've time, you can continue ditching into the camera issue or... enjoy the node.
Cheers.

**Comment by Supergiovane** [comment]
Sorry, the **1.0.45** is the right version!
