### ISSUE TITLE
Controlling NVR

### ISSUE THREAD

**Issue by ravelectrical** [Supergiovane/node-red-contrib-hikvision-ultimate#18]
Hi, was wondering is there a way to control the NVR instead of using the IR remote someway like up, down, left, right, channel numbers etc. This would be very helpful.

**Comment by Supergiovane** [comment]
Hi Ravel
Thank you for the suggestion, but this is out of the node’s scope and i’m pretty sure, this cannot be done with the hikvision api!

**Comment by ravelectrical** [comment]
Thanks for getting back to me never mind a great node well done keep up the good work.



Sent via the Samsung Galaxy Fold, an AT&T 5G Evolution capable smartphone



-------- Original message --------
From: Max Supergiovane ***@***.***>
Date: 6/15/21 6:24 AM (GMT+00:00)
To: Supergiovane/node-red-contrib-hikvision-ultimate ***@***.***>
Cc: ravelectrical ***@***.***>, Author ***@***.***>
Subject: Re: [Supergiovane/node-red-contrib-hikvision-ultimate] Controlling NVR (#18)


Hi Ravel
Thank you for the suggestion, but this is out of the node’s scope and i’m pretty sure, this cannot be done with the hikvision api!
