### ISSUE TITLE
Picture Node: Network timeout

### ISSUE THREAD

**Issue by GeorgWolter** [Supergiovane/node-red-contrib-hikvision-ultimate#2]
First of all I would like to say thank you and best from Germany👍

My cameras are abroad so I am using a VPN which works fine with http-access to cameras via Firefox and iVMS-4200.
Current issue: The picture node's attempt to connect to a camera leads to a timeout.

topic: ""
errorDescription: "network timeout at: http://192.xxx.xxx.xxx/ISAPI/Streaming/channels/101/picture"
payload: true

**Comment by Supergiovane** [comment]
Hello,
I think i should increase the timeout. I’ll do it sofort, so you can try.

**Comment by Supergiovane** [comment]
V 1.0.6 is out. The timeout is not 15 seconds. It should suffice.
Let me know. Thanks.

**Comment by GeorgWolter** [comment]
Great, that's performance👏
Just waiting that Nod Red is offering the V 1.0.6 in menu "Palette".

**Comment by GeorgWolter** [comment]
V 1.0.6 installed but it's still saying timeout.
Anything I should configure in the camera maybe?
Cameras I have: DS-2CD2T63G0-I8 AND DS-2CD2T85FWD-I8
![Bildschirmfoto 2020-12-13 um 20 16 33](https://user-images.githubusercontent.com/61526104/102021513-8ddb4d80-3d80-11eb-8e6f-cfd3767dc9e3.jpeg)

**Comment by Supergiovane** [comment]
Hmmmm... 15 seconds should be enough. The heartbeat fails as well some seconds later. 
What appens if you copy the URL of the first debug message, pasting it into web browser?

**Comment by Supergiovane** [comment]
And... can you issue a node -v command in a node-red console and tell me if you’ve at least Node v10.0.0 installed?

**Comment by Supergiovane** [comment]
Other than that, have you enabled the Isapi/CGI option in the camera?

**Comment by GeorgWolter** [comment]
- What appens if you copy the URL of the first debug message, pasting it into web browser?: **Works fine. I see the picture.**
- Result from node -v command: v12.20.0

**Comment by Supergiovane** [comment]
There is only the CGI thing. Can you check it?

**Comment by GeorgWolter** [comment]
- No success after activating CGI
- Time between calling URL and picture: < 1 second

**Comment by Supergiovane** [comment]
After installing the v1.0.6 have you restarted nodered?
If yes, how about changing the authetication from “digest” to “basic” in the config node and restart node-red?

**Comment by GeorgWolter** [comment]
- Yes, I have restared Node Red as requested
- Node: Changed authentication from “digest” to “basic”: Still timeout

**Comment by Supergiovane** [comment]
Tried yet with my VPN and all is fine.

<img width="1079" alt="Item-0_e_WiFi_e_Item-0" src="https://user-images.githubusercontent.com/37666636/102022265-f7118f80-3d85-11eb-9481-1066ddac07f3.png">

**Comment by GeorgWolter** [comment]
Strange 😊
I am running Node Red on a Raspberry Pi in my home network
And I have another instance running on DS720+ VMM (see issue #2)

**Comment by Supergiovane** [comment]
Do you maybe have WIFI and Ethernet both active on your PI?
You could disable the WIFI to see if it fixes the issue.

**Comment by GeorgWolter** [comment]
Pi: I am using a LAN / PoE-Hat. WiFi is not active.

**Comment by Supergiovane** [comment]
Ok, let me do some more checks tomorrow, once in office. I'll try to ditch into this issue. It's for sure related to some other timeout... I'll keep you posted.

**Comment by GeorgWolter** [comment]
👏 Thanks

**Comment by Supergiovane** [comment]
PS: in the meantime, revert to digest authentication ;-)

**Comment by GeorgWolter** [comment]
Raspberry / Browser: Not yet tested
My 3rd test-environment: DS-720+ with Node Red running in Docker: Node Installation works fine / no connection to cams.

**Comment by Supergiovane** [comment]
Hi Georg. 
Is nodered on docker able to reach the internet or you vpn? You should be sure thath the Raspi and nodered on synologi are able to reach other end of your vpn.

**Comment by Supergiovane** [comment]
Hi Georg. 
Is nodered on docker able to reach the internet or you vpn? You should be sure that the Raspi and nodered on synologi are able to reach the other end of your vpn where your cams resides.

**Comment by GeorgWolter** [comment]
Will verify that until tomorrow and I think you are completely right.

**Comment by Supergiovane** [comment]
Georg?

**Comment by GeorgWolter** [comment]
Hi, have thought through the infrastructure and realised that the problem lies here. Certainly not in your software.
Working on establishing a VPN Site-toSite connection from my Fritz!Box in Germany to my Site abroad (UniFi USG).

**Comment by Supergiovane** [comment]
Good luck. I ended up using opnSense on both ends to do a reliable openvpn connection. I had the same as you, fritzbox and usg.

**Comment by GeorgWolter** [comment]
Yes, I am facing the same trouble. I am close to saying good bye to my FB6590 and buy a Dream Machine Pro for Bremen.
How does your VPN infra (HW) look like?

**Comment by Supergiovane** [comment]
Hi Georg,
I have a star configuration. Due to the fact that my internet connection at home doesn't have a fixed IP, i bought a cloud subscription from Hetzner.com (or .de, i cannot recall now) for ca. Euro 3,00/Month with fixed IP. I istalled an opnSense firewall on this machine. OpnSense has OpenVPN client/Server built in. This machine works as OpenVPN Server.
Then for my home, i've installed a VM on my QNAP, with opnSense as firewall as well, with openVPN client to the Hetzner cloud machine. This give me a fixed IP for my home. My primary firewall is obviously the opnSense on the Hetzner cloud machine (because it "sees" my home's internal IP subnet, that is routable as well!).
At home of the mather of my wife (alone, because the father died 'cause of Coronavirus), i installed a **super very good Telkonika router** (it has two SIM slots and it can connect to a WAN as well , working as OpenVPN client: https://teltonika-networks.com/it/product/rutx11/). This Teltonika router is connected to a Fritzbox (working only as modem and a DECT server for phones in his house). This teltonika router connects with the Hetzner cloud machine as well, so from my home, i'm able to connect to the entire subnet of my wife's mother's home.
My only Unifi gears are switches and Access Points. Unifi routers are way so limited for my needs.

**Comment by GeorgWolter** [comment]
Thanks for the detailed description👍

**Comment by GeorgWolter** [comment]
Hi Giovane,
i see that the launch of REOLINK's new 4K RLC-810A and 510A is ongoing. Both got person and vehicle detection. 
Do you think you can develop nodes?

**Comment by Supergiovane** [comment]
Hi Georg,
nope sorry. I develop only for gears i own. I own only hikvision stuffs!

**Comment by GeorgWolter** [comment]
I See. Otherwise I would maybe send you a Reolink.

**Comment by GeorgWolter** [comment]
Giovane, buon Natale!
Just thought I'll let you know that I will get a DS-2CD2645FWD-IZS very soon.
So if you think that some testing would be from benefit for your projects then very welcome.

**Comment by Supergiovane** [comment]
Hi Georg
Wow, good! I’m sure they work flawlessy with hokvision-ultimate!

**Comment by GeorgWolter** [comment]
I'm very sure of that too👍

**Comment by GeorgWolter** [comment]
DS-2CD2645FWD-IZS is working well.
Should come up now in the compatibility list.

**Comment by Supergiovane** [comment]
Thank you. If you click “connect” in the config window, it will be automatically added here
www.supergiovane.it:8080/?read=true&md=noCD&fw=no
