### ISSUE TITLE
Constant disconnections on DS-K1T341AMF

### ISSUE THREAD

**Issue by beccsjb** [Supergiovane/node-red-contrib-hikvision-ultimate#21]
Hello! Firstly, let me thank you for such an amazing node! You've saved us all thousands of hours of sifting through API commands!

I'm experiencing constant disconnects on DS-K1T341AMF. The connection lasts for about 5 seconds, then seems to drop out for about 10-20 seconds. The devices in on the Local LAN, with no VLAN or firewall etc.

LAST DEVICE INFORMATION SAVED
Name: Access Controller
Model: DS-K1T341AMF
Firmware: V3.2.30

Are there any settings i need to change on the DS-K1T341AMF? Anyone else had experience with this? I see that its on the list of devices that are said to work.

The bug reproduces itself every 5 - 10 seconds. I've tried Alarm node, RAW node. They all disconnect.
I have also tried different ports using the ones listed in SADP tool, though it only connects on its web port which is set at 80.

As seen in the screen shots, a ping tells me that the device isnt dropping off the network etc.

Your help is greatly appreciated!

My goal is basically to see the devices alarm input state: ie Open or Closed door, see the relay state: open or closed and then to be able to control the relay state.

Thank you so much for taking the time to read my issues and hopefully someone has an answer for what i'm doing wrong :) 

![Screenshot 2021-07-09 091107](https://user-images.githubusercontent.com/43426367/125001406-e4e69e00-e095-11eb-8379-3b0d2ee9190c.png)
![Screenshot 2021-07-09 091225](https://user-images.githubusercontent.com/43426367/125001410-e617cb00-e095-11eb-92dc-eabadac30d67.png)
![Screenshot 2021-07-09 091153](https://user-images.githubusercontent.com/43426367/125001411-e6b06180-e095-11eb-9bb5-d72ccaab41ff.png)
![Screenshot 2021-07-09 091136](https://user-images.githubusercontent.com/43426367/125001412-e748f800-e095-11eb-97f9-d3216f5d9afc.png)
![Screenshot 2021-07-09 091123](https://user-images.githubusercontent.com/43426367/125001413-e7e18e80-e095-11eb-97ca-be559a97a14b.png)

**Comment by Supergiovane** [comment]
Hi
Thank you for using one of my nodes. 
Please be sure you installed the node v14 or anove and the latest node-red environment. 
As for node, you can check it by issuing “node -v” in a prompt window. 
As for nodered, you can check it bu viewing in the menu on the right.
