### ISSUE TITLE
feature request: self-signed certs

### ISSUE THREAD

**Issue by sgoudelis** [Supergiovane/node-red-contrib-hikvision-ultimate#22]
Hello,

I am trying to authenticate to my NVR over SSL and I am getting:

```
"Errore  hikvisionUltimateGetInfoCam request to https://192.168.1.56:443/ISAPI/System/deviceInfo failed, reason: self signed certificate"
```

Is there a way perhaps to disable the cert check or offer it as an option perhaps?

**Comment by Supergiovane** [comment]
Hi Stratos
That's strange. I've also an https connection, but i never had any issue.
Currently i'm on vacation and i cannot check it for you.
You should give me some time, i'll be back to home in august.

**Comment by sgoudelis** [comment]
Sure, take care..

**Comment by Supergiovane** [comment]
Hi Stratos
despite this issue, does the node work?

**Comment by Supergiovane** [comment]
Hi Stratos
despite this issue, does the node work?

**Comment by sgoudelis** [comment]
Yes it does with non-SSL authentication

**Comment by Supergiovane** [comment]
Hi 
i've made a "blind" change to a file. Are you able to paste the ZIP content, into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder, and restart node-red?
Please make a backup of your old Hikvision-config.js file before unzipping, so if in trouble, you can restore the old file.

[Hikvision-config.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/6817829/Hikvision-config.js.zip)

**Comment by sgoudelis** [comment]
Sorry, for the delay, I will check this out soon. Thank you

**Comment by Supergiovane** [comment]
Ok, please be aware that this file, works only with HTTPS.
If it runs OK, i've already done the properly changes to work on both http and https.
Please let me know if it works. If yes, i'll publish the updated version on npm.
Thanks

**Comment by sgoudelis** [comment]
Yeah that worked. Thank you very much!
