### ISSUE TITLE
DS-KV6113-WPE1(B)  no event

### ISSUE THREAD

**Issue by ur5zeb** [Supergiovane/node-red-contrib-hikvision-ultimate#23]
node alarm  does not receive a message.
hik connect is working fine

**Comment by Supergiovane** [comment]
Not sure if the DS-KV6113-WPE1 uses the same protocol. I've no DS-KV6113-WPE1 to test, sorry!
Have you other hik cameras that are working?
Please say at least "Hello".

**Comment by Supergiovane** [comment]
Yet i'm on holiday and i'll return home in about 10 days. So i cannot help you now.
In the meantime, try to use the RAW alarm node and see what it outputs as soon as someone triggers a motion on your doorbell.

**Comment by ur5zeb** [comment]
I am using node RAW.  I don't receive any messages from the node :(
Is it possible to receive an event from hikconnect
Have a nice holiday!

**Comment by ur5zeb** [comment]
Hi!  using isapi you can get the state of the doorbell

curl -i --digest -u admin:xxx http://192.168.x.x/ISAPI/VideoIntercom/callStatus?format=json

Should give as output : “idle” , “ring” , “onCall”

**Comment by Supergiovane** [comment]
Good, thank you. As i can see, the endpoint is totally different from the cameras.
I'll work on that as soon as i come back home from holidays.

**Comment by ur5zeb** [comment]
thanks, I'll wait!  there are also methods for opening the lock and receiving a stream. I found information.  here https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535  thanks again for your work

**Comment by Supergiovane** [comment]
Thank you.
Are you able to post here the complete json returned by curl? As i'm on holidays, i've no access to any real doorbell to test.
Most probably, i'll add another node "Doorbell", so i can handle all things related to videointercom.

**Comment by ur5zeb** [comment]
Yes, sure.  I'll do it in the evening.  ready to participate in testing on hardware

**Comment by ur5zeb** [comment]
JSON 
{
        "CallStatus":   {
                "status":       "idle"
        }
}

**Comment by Supergiovane** [comment]
Thanks. Will take a look next week. Then i’ll send you some files to test :-)

**Comment by ur5zeb** [comment]
OK. thanks
I will see additional ISAPI methods that work

**Comment by Supergiovane** [comment]
Hi ur5zeb
if needed, would you have the chance to temporary open a port forward from the internet to your hik intercom for me to test something?

**Comment by ur5zeb** [comment]
Hi.  yes I can open port 80. but only after a few hours

**Comment by Supergiovane** [comment]
Ok, thanks. If able, please protect the access with an username and password, so you won't risk someone sniffinf your device.

**Comment by ur5zeb** [comment]
do you have a viber or telegram?

**Comment by Supergiovane** [comment]
Sorry nope! But you can write me at maxsupergiovane@icloud.com

**Comment by Supergiovane** [comment]
Thanks, it's too early to check motions and stuffs like that.
For now I'm focusing to obtain info/capabilities and to grab the intercom ringbell stream.
I'm still on holidays with partial access to internet!
I'll keep you posted.
Many thanks for your help. :-)

**Comment by ur5zeb** [comment]
Thank you. I am also studying KFOR now. I'm trying to make a wall panel from an android tablet with the interface I need. Already it turned out to make an activity with a real-time stream

**Comment by Supergiovane** [comment]
Ok, the idle/oncall/ring stream should be OK.
Tomorrow i'll proceed further. In the meantime, thanks.

<img width="352" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/132379564-bd846d54-6ac5-498d-a9e4-6b3f9bf9c60f.png">

**Comment by ur5zeb** [comment]
I am blocking access from the Internet. When you need to tell me, I can open access at any time from my smartphone

**Comment by Supergiovane** [comment]
Hi
can you open the port for me until 13.00 o' clock?

**Comment by ur5zeb** [comment]
нI.
we have no internet throughout the city. 
I will let you know when they solve the problem

**Comment by ur5zeb** [comment]
Port open

**Comment by Supergiovane** [comment]
Hi,
you can close the port for now. Thank you.
Can you please unzip this file into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7128884/Archivio.zip)

and this zip into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate** folder 
[package.json.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7128887/package.json.zip)

and restart node-red?
You should see a new doorbell node (colored in red).
Can you try it and let me know if it's working?
The node is still in beta. Currently the opening door function is not implemented.
Thanks.

PS: if you're in trouble, you can still re-install an older version.

**Comment by ur5zeb** [comment]
ok thanks.  I'll try in the evening

**Comment by ur5zeb** [comment]
Hi. Things are good. When the doorbell rings, I get the message true.
Could you please help link the doorbell and homekit

**Comment by ur5zeb** [comment]
I created a thread.
Everything works, but notifications go to the iPhone while the doorbell rings. how to make sure that the message would come once or put the delay on the survey after the first call


[
    {
        "id": "462d866fd91fd3d0",
        "type": "tab",
        "label": "Дверной звонок",
        "disabled": false,
        "info": ""
    },
    {
        "id": "6b3838b11f603ab8",
        "type": "hikvisionUltimateDoorbell",
        "z": "462d866fd91fd3d0",
        "name": "",
        "topic": "",
        "server": "09465624358080ae",
        "ringStatus": "all",
        "floorNo": "all",
        "unitNo": "all",
        "zoneNo": "all",
        "buildingNo": "all",
        "x": 660,
        "y": 600,
        "wires": [
            [
                "ab62b63befe7ace0",
                "5056ae7de76f9f50",
                "306e5021e8c8e0de"
            ],
            [
                "98b5452734ee9c0f"
            ]
        ]
    },
    {
        "id": "306e5021e8c8e0de",
        "type": "debug",
        "z": "462d866fd91fd3d0",
        "name": "msg",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 920,
        "y": 560,
        "wires": []
    },
    {
        "id": "98b5452734ee9c0f",
        "type": "debug",
        "z": "462d866fd91fd3d0",
        "name": "error",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 920,
        "y": 620,
        "wires": []
    },
    {
        "id": "ab62b63befe7ace0",
        "type": "homekit-service",
        "z": "462d866fd91fd3d0",
        "isParent": true,
        "hostType": "1",
        "bridge": "",
        "accessoryId": "d36fc8e62a5c8935",
        "parentService": "",
        "name": "doorbell_switch",
        "serviceName": "Switch",
        "topic": "",
        "filter": false,
        "manufacturer": "NRCHKB",
        "model": "1.3.6",
        "serialNo": "Default Serial Number",
        "firmwareRev": "1.3.6",
        "hardwareRev": "1.3.6",
        "softwareRev": "1.3.6",
        "cameraConfigVideoProcessor": "ffmpeg",
        "cameraConfigSource": "",
        "cameraConfigStillImageSource": "",
        "cameraConfigMaxStreams": 2,
        "cameraConfigMaxWidth": 1280,
        "cameraConfigMaxHeight": 720,
        "cameraConfigMaxFPS": 10,
        "cameraConfigMaxBitrate": 300,
        "cameraConfigVideoCodec": "libx264",
        "cameraConfigAudioCodec": "libfdk_aac",
        "cameraConfigAudio": false,
        "cameraConfigPacketSize": 1316,
        "cameraConfigVerticalFlip": false,
        "cameraConfigHorizontalFlip": false,
        "cameraConfigMapVideo": "0:0",
        "cameraConfigMapAudio": "0:1",
        "cameraConfigVideoFilter": "scale=1280:720",
        "cameraConfigAdditionalCommandLine": "-tune zerolatency",
        "cameraConfigDebug": false,
        "cameraConfigSnapshotOutput": "disabled",
        "cameraConfigInterfaceName": "",
        "characteristicProperties": "{}",
        "waitForSetupMsg": false,
        "outputs": 2,
        "x": 950,
        "y": 720,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "5056ae7de76f9f50",
        "type": "hb-status",
        "z": "462d866fd91fd3d0",
        "name": "doorbell Doorbell Trigger",
        "Homebridge": "homebridge",
        "Manufacturer": "Homebridge",
        "Service": "Switch",
        "device": "homebridge0E:5E:97:28:D3:15Homebridgedoorbell Doorbell Trigger00000049",
        "conf": "1a34d16d52370652",
        "x": 800,
        "y": 340,
        "wires": [
            [
                "0889648e69fe2d8e"
            ]
        ]
    },
    {
        "id": "c688e80e10913a4d",
        "type": "hb-control",
        "z": "462d866fd91fd3d0",
        "name": "doorbell Doorbell Trigger",
        "Homebridge": "homebridge",
        "Manufacturer": "Homebridge",
        "Service": "Switch",
        "device": "homebridge0E:5E:97:28:D3:15Homebridgedoorbell Doorbell Trigger00000049",
        "conf": "1a34d16d52370652",
        "outputs": 0,
        "x": 1330,
        "y": 220,
        "wires": []
    },
    {
        "id": "0889648e69fe2d8e",
        "type": "function",
        "z": "462d866fd91fd3d0",
        "name": "",
        "func": "\nvar ret_msg=msg;\nret_msg.payload.On = !msg.payload.On;\nreturn ret_msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1030,
        "y": 340,
        "wires": [
            [
                "c688e80e10913a4d"
            ]
        ]
    },
    {
        "id": "09465624358080ae",
        "type": "Doorbell-config",
        "host": "192.168.80.80",
        "port": "80",
        "name": "Doorbell",
        "authentication": "digest",
        "protocol": "http",
        "heartbeattimerdisconnectionlimit": 1,
        "deviceinfo": "[object Object]"
    },
    {
        "id": "d36fc8e62a5c8935",
        "type": "homekit-standalone",
        "accessoryCategory": "8",
        "bridgeName": "",
        "hostType": 1,
        "pinCode": "243-68-697",
        "port": "56989",
        "allowInsecureRequest": false,
        "manufacturer": "NRCHKB",
        "model": "1.3.6",
        "serialNo": "Default Serial Number",
        "firmwareRev": "1.3.6",
        "hardwareRev": "1.3.6",
        "softwareRev": "1.3.6",
        "customMdnsConfig": false,
        "mdnsMulticast": true,
        "mdnsInterface": "",
        "mdnsPort": "",
        "mdnsIp": "",
        "mdnsTtl": "",
        "mdnsLoopback": true,
        "mdnsReuseAddr": true,
        "allowMessagePassthrough": true
    },
    {
        "id": "1a34d16d52370652",
        "type": "hb-conf",
        "username": "906-84-792"
    }
]

**Comment by Supergiovane** [comment]
Hi
Good. 
Please be aware that i’m still working on that, this is a beta version that must be refined. 
Yet i cannot check your flow, because i’m still on holidays. I will check it next week as i come home. 
I need you to again open the port for me. 
I’ll keep you informed as soon as i need it!
Thanks.

**Comment by ur5zeb** [comment]
ok i will open the conda port you need

**Comment by Supergiovane** [comment]
Hi again,
Please unzip this file into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder and restart node-red. This avoids the node repeatedly emit same messages multiple times.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7135107/Archivio.zip)

**Comment by Supergiovane** [comment]
Sorry, this is the right ZIP

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7135129/Archivio.zip)

**Comment by Supergiovane** [comment]
Hi
i'm ready to open your main door (your home's door).
Please let me know when i can test that.

**Comment by ur5zeb** [comment]
Port open

**Comment by Supergiovane** [comment]
Yes but, are you at home? I wish to OPEN YOUR HOME DOOR, your phisycal door, anyone can enter!

**Comment by ur5zeb** [comment]
everything is ok, I have not connected the lock yet :)

**Comment by Supergiovane** [comment]
Nope. I must check some things... i'll reverto to you soon.

**Comment by ur5zeb** [comment]
ok i say i will go to the door to hear the message that the door is open

**Comment by ur5zeb** [comment]
is it possible to make a full doorbell node with two-way audio video stream and native homekit support :) now I have a separate homebridge on rasberripi 3  for video streaming

**Comment by Supergiovane** [comment]
Hi,
does the unlock relais something? It should unlock.

**Comment by ur5zeb** [comment]
I go to the door, try

**Comment by ur5zeb** [comment]
the lock opened. Everything is ok

**Comment by Supergiovane** [comment]
Ok, thanks. The next thing is to stop your intercom ringing.
As soon as i've done that (hope some minutes), i'll tell you what to do.
Thanks

**Comment by ur5zeb** [comment]
I have now replaced two doorbell files from the last archive and my doorbell assembly is missing from the list

**Comment by Supergiovane** [comment]
Let me finish. Then i'll send you other files.
Please, push ring button. It should stop ringing after some 2-3 seconds.

**Comment by ur5zeb** [comment]
I pressed

**Comment by Supergiovane** [comment]
Does it stop ringing after 4 or 5 seconds?

**Comment by ur5zeb** [comment]
No, he calls until you press the button

**Comment by Supergiovane** [comment]
Sorry, i was temporary offline. Try now.

**Comment by Supergiovane** [comment]
It should completely stop ringing.

**Comment by ur5zeb** [comment]
No, it rings until you press the call button
Can I stop my node-red

**Comment by Supergiovane** [comment]
Yes, you can stop it.

**Comment by ur5zeb** [comment]
I stopped. I'm going to ring the doorbell

**Comment by ur5zeb** [comment]
no, he doesn't stop calling

**Comment by Supergiovane** [comment]
Ufff...... Maybe your doorbell doesn't support API V2.0.
Have you an idea, where can i find the ISAPI V1.0 doorbell documentation?

**Comment by ur5zeb** [comment]
Protocol 1.0 was enabled in the Intercom Session Settings.It turned it off now, let's try

**Comment by Supergiovane** [comment]
Ok, please ring

**Comment by ur5zeb** [comment]
The HikConnect application stops ringing, but the deputy call continues to ring. What do you see in the logs

**Comment by Supergiovane** [comment]
Hmmm. No, i see the "RING" message but nothing else. The stunning thing is that the "stop ring" command is executed and your intercom gives me "OK". It should return "ERROR" if it cannot stop ringing.

**Comment by Supergiovane** [comment]
So it appears that only the clients stops ringing, but the intercom itself continues to be on ringing state.

**Comment by ur5zeb** [comment]
It turns out that yes

**Comment by Supergiovane** [comment]
Ok, maybe i found something interesting.
Tomorrow i'll continue to the stop ringing tests.
Here the files to be unzipped into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder and restart.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7137572/Archivio.zip)

In the README page on gitHub there are the commands to open the door.

**Comment by ur5zeb** [comment]
Thanks. I am closing the port. Tomorrow, let me know that you opened the port and was at home, pressing the bell :)

**Comment by ur5zeb** [comment]
At what interval did you make duplicate posts? I pressed the button, a notification came, I pressed the button, canceled the swap. I pressed the button again the message did not come

**Comment by Supergiovane** [comment]
Each two seconds i check for the status

**Comment by Supergiovane** [comment]
Please unzip this. There was a glitch. Testing things on remote internet connection is very hard.
[hikvisionUltimateDoorbell.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7137791/hikvisionUltimateDoorbell.js.zip)

**Comment by Supergiovane** [comment]
Hi again.
As soon as you wish, i'm ready to try to stop ringing your intercom.

**Comment by ur5zeb** [comment]
I'm at work now.  I'll let you know when I'm ready

**Comment by Supergiovane** [comment]
No problems. You can try by yourself when a home.
Just unzip this file and restart.
Pass **msg.hangUp = true** to the node. It should hangup the intercom call.

[hikvisionUltimateDoorbell.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/7142357/hikvisionUltimateDoorbell.js.zip)

Then please let me know if it's working.

**Comment by Supergiovane** [comment]
Ok, uploaded. Many thanks.

**Comment by ur5zeb** [comment]
Hi!
The command msg.hangUp = true  stops ringing the doorbell, but the call continues in the Hikconnect application

**Comment by Supergiovane** [comment]
Ok that’s not an issue. I’ll stop both. Thanks. 
I keep you posted as soon as i’ve done the changes

**Comment by ur5zeb** [comment]
Are you programming an Android studio?
I'm trying to get two-way audio of the doorbell, but I get an error :(

**Comment by Supergiovane** [comment]
No sorry!

**Comment by Supergiovane** [comment]
Hikvision Ultimate 1.0.52 is out.
It should address your issues. You can install it via Node-Red Palette's Menu.
Many thanks for your help in testing all the things!
