### ISSUE TITLE
Annke Camera

### ISSUE THREAD

**Issue by EvertDekker** [Supergiovane/node-red-contrib-hikvision-ultimate#24]
Hi,

Thanks for your amazing Node-red node, works great for me.

No bug to report, just small note.
I'm using Annke camera's, It's not sure where these camera's are made, but the software is full Hikvision compatible and looks the same as Hikvision. Think that Annke is a OEM from Hikvision.
Even the service tools like "Batch Configuration" from Hikvision works with these Annke camera's.

![Capture](https://user-images.githubusercontent.com/5690965/132055986-741d3c80-7d55-4ba9-957d-9c0608cd6e96.PNG)

So this makes the Hivision text in the above box is not correct for Annke and after pressing Yes the camera type is add to your tested device [list](http://80.211.147.27:8080/?read=true&md=noCD&fw=no) , amazing idea.
This will make your tested device list not only Hikvision devices.

If you want to correct this totally not important issue let me know and I'm willing to help you with testing.

node-red-contrib-hikvision-ultimate 1.0.51

Grazie

**Comment by Supergiovane** [comment]
Hi
Thanks for the suggestion. Yes there are many brands out there, based on hikvision. I’ll correct the texts!
