### ISSUE TITLE
Picture Grab from Mainstream

### ISSUE THREAD

**Issue by EvertDekker** [Supergiovane/node-red-contrib-hikvision-ultimate#25]
Hi,
Thanks again for your very nice nodes, it works great with my camera's

I noticed the grabbed picture is 624x482 pixels in size. From this size and the quality of the picture I assume that the picture is grabbed from the substream.
Is it possible to grab the picture form the mainstream so we can have a better quality picture?

Ver. 1.0.53

**Comment by Supergiovane** [comment]
Hi 
What camera model  are you using?

**Comment by EvertDekker** [comment]
Hi,
Anneke C500 I51DE

**Comment by Supergiovane** [comment]
Hi
There are many limitation on hikvision API to get an image. For example, you cannot choose the stream.
So what you get is what the camera gives via the API. If you haven't do any cropping in the configuration window, you can olny get such as maximum resolution, sorry.

**Comment by EvertDekker** [comment]
Hi,
Tried that url before, but it gives me the low resolution picture. I understand that not everything is possible with the ISAPI.

Using now ffmpeg in an exec node to grab a picture from the main stream, so I will keep on using that.

Thanks again for all your nice NR nodes.
