### ISSUE TITLE
Where can I learn about configuring Hikvision motion alarms?

### ISSUE THREAD

**Issue by hepcat72** [Supergiovane/node-red-contrib-hikvision-ultimate#30]
I have a new(ish) Annke camera that uses hikvision software. I'd been in contact with Annke support about how to get motion alarms working (among addressing other things/bugs) and was rather frustrated that they would only suggest enabling "Platform Access", which I don't want to do - I don't want to rely on a remote service for motion. They also constantly tell me to install an additional "vision" software for recording - but I already use an alternate paid software (Sighthound Video Pro) and have been for years - and am happy with it.  When I complained to them that the motion emails were only triggering at night (when the IR was on), their solution was repeatedly: enable platform access. It seems that that's their cure-all for every issue.

But after I found your node, I was able to get motion alarms into my node-red setup, which is great... and I'm getting motion alarms and emails now during both day and night, but the motion alarms go off on average once a minute when nothing is happening. Even when I turned the sensitivity down to 1, it had no effect on the frequency of the motion alarms.

So I thought I would ask you what a good source is for figuring out how to tweak the motion event settings...

**Comment by Supergiovane** [comment]
Hi
I’ve no clue on Annke. You can use the RAW alarm node to inspect what happens
