### ISSUE TITLE
New feature to pull recorded images / video 

### ISSUE THREAD

**Issue by smcgann99** [Supergiovane/node-red-contrib-hikvision-ultimate#32]
Hi,

I'm working on a flow to grab a still image on an alarm and store on my PI4 for easy verification. I'm sure it would be possible to get this from the DVR directly based on timestamp, camera channel etc. I don't have any good info on the API and its probably beyond my skills. 
Do you have any plans for something like this ?

**Comment by Supergiovane** [comment]
Hi
Yes you van do it using the picture node, but better asking on nodered forum, as i’m very busy with another of my nodes and i cannot currently halp you!

**Comment by smcgann99** [comment]
Sorry I didn't explain very well.

I mean to grab an image from the "past" based on a timestamp, not a live image. Also video clips would be great ;-)

**Comment by Supergiovane** [comment]
Hi,
Ok, understood. 
No, currently is not possible. Maybe you can achieve that by using the XML Node and pass the needed data to it. You should search for what to pass, in the use-ip website forum or in the ipcamtalk website forum.
