### ISSUE TITLE
FR: Calling PTZ-Prreset by number from payload

### ISSUE THREAD

**Issue by ozett** [Supergiovane/node-red-contrib-hikvision-ultimate#33]
Salutation "Hello" Supergiovane

**Describe the bug**
Wondering if i need for each preset a PTZ-Node with the PTZ-Preset "preset" in that node

**Expected behavior**
maybe possible to send the preset-number with payload to call the preset?
i.e. payload=1,   (for preset 1) ?

**Screenshots**
![image](https://user-images.githubusercontent.com/5937811/143617327-19daefa2-e826-4a23-aad7-e0c982c12b68.png)

**Hikvision-Ultimate Version**
 1.1.95
Node-Red running on ubuntu in vmware

**Additional context**
did not try it out, but did also found no documentation.

**Comment by Supergiovane** [comment]
Hi ozett,
node-red-contrib-hikvision-ultimate@1.0.57 is out.
In the README you'll find how to recall the preset.

```javascript
// Pass the Camera Number and PTZ preset by message
msg.payload.channelID = 1; // OPTIONAL, pass the Camera number
msg.payload.PTZPreset = 2; // OPTIONAL, pass the PTZ preset number
return msg;
```

**Comment by ozett** [comment]
thanks for putting this in. great.
you may want to add some hints in further verision to that node,
that this is possible?

![image](https://user-images.githubusercontent.com/5937811/143676459-2576ae9f-15cd-458c-98e8-229de2b7dc8a.png)

**Comment by Supergiovane** [comment]
Hi
Yes can be a good idea, but it may be better to go to the README file…
