### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by ur5zeb** [Supergiovane/node-red-contrib-hikvision-ultimate#34]
Hello.  I wish you a Happy New Year and Merry Christmas.  I would like to suggest adding functionality to your site if possible.
 1. To the alarm node input action for arming and disarming
 2.To the doorbell node the method associated with the RFID tag reader
 3. There was an idea to implement the possibility of arming / disarming by reading the tag on the doorbell :)
 4. From the equipment that I have on the network, this is the called ds-kv6113 panel, ds-kb6320 monitor, ax pro hub
   Regards, Oleg.

**Comment by Supergiovane** [comment]
Hi Oleg
Happy new year to you too.
Thanks for the sugestions, i'll take a look but i'll take time as i'm currently committed on changes to my KNX-Ultimate node.
In the meantime, for arming/disarming you should try the XML node. It's able to send any command, if you know what to send.
As for the RFID, you could try to use the RAW Alarm node and see if you can trap the RFID event.

As i don't own any AX PRO nor any Hikvision doorbell, as soon as i'm ready to do these changes, i need a connection to your system via Internet, for testing pourposes!
