### ISSUE TITLE
No connect with DS-7616NI-I2

### ISSUE THREAD

**Issue by Cm-8** [Supergiovane/node-red-contrib-hikvision-ultimate#38]
Hello!

**Describe the bug**
I try to connect to a DS-7616NI-I2 with firmware V4.22.005 build 191208 without success.
There is a minimun firmware version?

**Screenshots**
![image](https://user-images.githubusercontent.com/21364091/174636658-d0597852-60c2-4d71-a4e4-b5184c214018.png)

**Hikvision-Ultimate Version**
 - 1.0.62

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running alone in Ubuntu 20.04.4 LTS linux-virtual-machine on vmware
 - Node v: 16.14.2

Thanks

**Comment by Supergiovane** [comment]
Ciao Ale
do you have enabled the API on the NVR? I've the same NVR and it works without issue.
Does the log say something?
Please also paste the flow, so i can reproduce it on my machine. Thanks.

**Comment by Cm-8** [comment]
Ciao Supergiovane!

Solved setting the port to 80 (and not to the port used by the client iVMS)
