### ISSUE TITLE
RAW Alarm, Alarm not Connects

### ISSUE THREAD

**Issue by duyuelryel** [Supergiovane/node-red-contrib-hikvision-ultimate#39]
Greetings!
I have a kv8113 doorbell. 
When i use the Doorbell node, i can controll it as open the doors or hang up the call. But can't connect to it as a server as the Alarm or the RAW Alarm node needs to. The default port is 8000 what is opened on the device but after updating the setting in the node, it keep saying :

Problem reading infostream from camera: {"message":"request to http://192.168.1.114:8000/ISAPI/System/deviceInfo failed, reason: read ECONNRESET","type":"system","errno":"ECONNRESET","code":"ECONNRESET"}. Check your credentials and connection properties.

I'm sure the credentials are correct, it works on the Doorbell node.
What did i miss or where should i set some other config? Maybe i didn't set someting on the 8113 config?

Thank you!

**Comment by Supergiovane** [comment]
Hi
It seems that your doorbell sends a connection reset to the node. 
Check how many concurrent connections your doorbell does support. 
Other than that, i’m not totally sure that the api entrypoint for doorbell alarm, is the same as the ip camera.

**Comment by duyuelryel** [comment]
> Hi It seems that your doorbell sends a connection reset to the node. Check how many concurrent connections your doorbell does support. Other than that, i’m not totally sure that the api entrypoint for doorbell alarm, is the same as the ip camera.

thank you for the reply! I have disabled all other nodes but the RAW Alarm node but it's the same. I think the number of connection isn't the problem.
Doorbell node connected witouth problem.
The rest first "waiting for connection", then "connecting", then "Unauthorized".
 
![Képernyőfelvétel (62)](https://user-images.githubusercontent.com/11785363/179207307-35643aaf-48f3-449e-9e67-377e07bfa2a8.png)

**Comment by Supergiovane** [comment]
Hi
unfortunately, i haven't your doorbell to test with, so currently i cannot help you.
You should look in the node-red log, because "unauthorized" means that your doorbell doesn't allow the node to do some things that have to be authorized.
