### ISSUE TITLE
Missing end of alarm

### ISSUE THREAD

**Issue by gbarocsi** [Supergiovane/node-red-contrib-hikvision-ultimate#40]
Hi!
I think this is a very outstanding project and very very useful!
I could setup my NVR without a problem and connection is stable.
My problem is, that I don't see anything related to event end. Nor in RAW Alarm.

I used a hikvision->mqtt script running on my linux server and I receive a message when an triggered alarm ends but I don't see it here. always see true as output. For one alarm case I see multiple true messages, then nothing. At the next alarm situation I get another bunch of true messages, then nothing. I tried local alarm input as well.
Can you please help if I misconfigure something?
Thank you very much!

**Comment by Supergiovane** [comment]
Hi
In normal events, like "movement", there is only a "true" message. 
In smart events, there should be "true" for alarm and "false" for end of alarm.
If you don't see the "false" message even in the RAW alarm, your camera is not sending such message.
I suggest you to simply handle only the "true" message. 
:-)

**Comment by gbarocsi** [comment]
Hi!
I can't see it in RAW. Allright I'll handle it using timers. Thanks! :)
I checked in the mqtt messages, I get "active" for VMD and "inactive" after a while.

My other question: is that normal that multiple true messages arrive?
Thanks!

**Comment by Supergiovane** [comment]
Hi
yes and it depends on the event type and camera type/firmware.
There are a lot of different behaviours in each hik camera/NVR. It's really a mess!

**Comment by gbarocsi** [comment]
Allright, thanks a lot and keep going with the project! :)
