### ISSUE TITLE
Door Station DS-KV8213-WME1

### ISSUE THREAD

**Issue by SimonePariani** [Supergiovane/node-red-contrib-hikvision-ultimate#41]
Ciao Supergiovane,
I have the doorstation DS-KV8213-WME1 (Firmware V2.1.5), I need to receive doorbell notification, see the pictures from the camera and open the door.
Now I can only open the door, The doorbell is connected but the debug node doesn't show any event when I press the button on the unit.
The Picture node retrieve server informations but has a red dot with "not found" and no pictures are received.
No other HIKVision units are in the network.

**Screenshots**

![image](https://user-images.githubusercontent.com/110744707/183266318-73895ffa-b986-4fdb-bf32-5b28f3106414.png)

![image](https://user-images.githubusercontent.com/110744707/183266337-c4937301-132a-486b-9e57-c009f5da5cbc.png)

This is the doorbell node configuration:
![image](https://user-images.githubusercontent.com/110744707/183266521-0da51ce2-eaa5-4c5e-b41f-9c20ec6cb8ce.png)

This is the picture node configuration:
![image](https://user-images.githubusercontent.com/110744707/183266536-699b6128-c46c-4604-adec-f7a6dfa56d87.png)

**Hikvision-Ultimate Version**
 - 1.0.62

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red v14.18.1 running alone in RaspberryPi

Many thanks in advance
and Forza Italia!

**Comment by Supergiovane** [comment]
Hi Simone
Every hik door station has its own firmware and api version. Unfortunately, i haven’t your particular model to test with, so i have no clue on what the node doesn’t find nor why. 
I see the “Campanello” node having a red triangle. You should check, because you have some required fields non filled in. 

If you’re able to put your doorbell on the internet with some port forwarding, i should be able to debug your door station, but not now, because i’m on holiday! I’ll come back on 15 August!

**Comment by SimonePariani** [comment]
Ciao Supergiovane,
Grazie mille per la tua disponibilità.
Di quali porte hai bisogno?
Come ti posso mandare i dati per l’accesso… senza farli sapere a mezzo mondo? 😊

Buone ferie.

Simone

Da: Supergiovane ***@***.***>
Inviato: domenica 7 agosto 2022 06:58
A: Supergiovane/node-red-contrib-hikvision-ultimate ***@***.***>
Cc: Simone Pariani ***@***.***>; Author ***@***.***>
Oggetto: Re: [Supergiovane/node-red-contrib-hikvision-ultimate] Door Station DS-KV8213-WME1 (Issue #41)


Hi Simone
Every hik door station has its own firmware and api version. Unfortunately, i haven’t your particular model to test with, so i have no clue on what the node doesn’t find nor why.
I see the “Campanello” node having a red triangle. You should check, because you have some required fields non filled in.

If you’re able to put your doorbell on the internet with some port forwarding, i should be able to debug your door station, but not now, because i’m on holiday! I’ll come back on 15 August!

**Comment by Supergiovane** [comment]
Ciao Simone
La porta ora non me la ricordo, te la dirò poi;  comunque fai con calma perché prima del 15 Agosto, non riesco a darci un’occhiata. 
La mia mail è maxsupergiovane@icloud.com
