### ISSUE TITLE
Connection issues - basic stuff

### ISSUE THREAD

**Issue by giluriel** [Supergiovane/node-red-contrib-hikvision-ultimate#42]
Hi,
I'm trying to use this addon, but I'm missing some basic info (probably important for everyone that would try..)
I'm using the DS-8003 Door station (with additional keypad). current firmware: 2.2.56 build 220713

in the **doorbell** node I'm getting "Waiting for event".
Clicking on Connect (Get info) - Brings up the unit's info so the connection is OK I guess.
But - no event happens when pressing the call button the the door unit and it say "calling failed"
In the **RAW alert** node I get "Unauthorized" (and here too - connect brings the right info).

To understand the workflow of the units (and hens the node red modules):

1. Does the 8003 has a setting of "who is" the control station and it sends events to this location?
    Or does the control (node red for this example) logs into the 8003 and "samples" it for events?
    
2.  On the 8003 - there are a couple of setting the confuses me:
(basic settings>port> I have http & https ports which are for contacting the unit. BUT what is server port? 
also
Under "Intercom" there are "registration password", "main station IP" and "Private server IP"
Does any of these has something to do with this implementation? I need to set something related?

3. do we need to setup specific user on the 8003? some special permissions? or the regular admin is OK?

Last one :) What firmware versions seem to be working correctly ? maybe I'll downgrade if it will help 

Many thanks :)
Gil

**Comment by Supergiovane** [comment]
Hi
Unfortunately your door station does not exposes the needed endpoint API. There is nothing you can do but waiting for firmware updates.
