### ISSUE TITLE
About deployment and withdrawal

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-hikvision-ultimate#44]
Hi @Supergiovane 
you are awesome
Unexpectedly, you are also using the products of hikvison
I have an NVR. I want to ask if I can implement the command of deploying and removing defense

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi Songzh!
Yes, of course. I wait your Pull Request on that.

**Comment by songzh96** [comment]
There may be a problem with the translation software. 😂 
I mean, does your plug-in currently support deployment and removal?
And where do you see the device API? Maybe I can try it myself

**Comment by Supergiovane** [comment]
Hi,
sincerely, i don't recall if it's possible. You should look into the readme page if it's possible. I'm out for some days and i cannot take a deep look into that. I found the PDF with the hikvision api, on the internet, by searching "HIKVISION ISAPI", but i don't recall where!

**Comment by songzh96** [comment]
OK
Thank you very much for your help 👍
