### ISSUE TITLE
Can see preview picture but node always has bad request

### ISSUE THREAD

**Issue by AnthK1973** [Supergiovane/node-red-contrib-hikvision-ultimate#45]
Hi Supergiovane,

Thanks for your work on the nodes - I am trying to setup the picture node so I can email a picture to myself when motion is detected.

My issue is: 
- I can setup the picture node and obtain a picture under "refresh picture" - no issues
- When I deploy - the node continually shows "Bad Request".

I don't need to do anything else to reproduce the error

I would expect that if I can see a picture when configuring the node that this would use the same connection to the NVR so I am unsure why it would not connect to the unit outside of the configuration window.

**Hikvision-Ultimate Version**
 - 1.0.64
 -
![Server1](https://user-images.githubusercontent.com/106218955/203226362-aa39d923-99d8-469e-8c03-944874bfbd31.png)
![Server](https://user-images.githubusercontent.com/106218955/203226364-88d4f8e2-1154-4465-b8a8-4f4995d153bc.png)
![deployed](https://user-images.githubusercontent.com/106218955/203226367-f6e7d675-17df-4adf-8e47-5005431a0d6f.png)
![Picture 1](https://user-images.githubusercontent.com/106218955/203226370-c051aa27-fb29-4c58-983d-73d304fc3027.png)

Node-Red running on RaspberryPi

**Comment by Supergiovane** [comment]
Hi,
what are you passing as message to the picture node? What is the payload of that "Email setup" node?

**Comment by AnthK1973** [comment]
Just a timestamp. But even before I trigger it - it won't connect.

Thanks

**Comment by Supergiovane** [comment]
I need a log, because that's not normal.
Just type banana after the server ip, in your case **10.0.0.50banana** then send me please the log.

**Comment by Supergiovane** [comment]
Hi
that row tells me nothing. I need you to do what i asked for, to enable the full detailed log.
Other than that, i need to know your node version and your node-red version also.
Thanks

**Comment by Supergiovane** [comment]
Hi
the log coming from node-red, like this one.
<img width="568" alt="massimosaccani_—_-zsh_—_80×39" src="https://user-images.githubusercontent.com/37666636/203265729-a79459e5-28d7-4905-88cc-7d4b9ca74c8b.png">

If you're unsure where to find it, please take a look on the node-red website, but usually it is in yout home directory, under **.node-red** folder.

**Comment by AnthK1973** [comment]
Hi,

I couldn't find the log but I did get the picture working and sending to my
email!
As I have an NVR I needed to use the port for the specific camera (i.e.
10.0.0.50:65002 rather than 10.0.0.50:80)

I copied the flow for a second camera and setup another hikvision node
(with 10.0.0.50:65003). For some reason though this just says "waiting for
event"

[image: image.png]

Any suggestions?

Thanks.

**Comment by Supergiovane** [comment]
Hi
ok, i've understood that your NVR has POE and it does NAT the cameras on different ports.
Please be sure that the NVR allows the port 65003 to be accessed.
It's useful to have a screenshot of your non working flow and the flow code itself (just select all nodes, then select "export" in the Node-Red right menu.
Then paste the code here, surrounding it with the "<>" option you find in this text editor. Don't worry, the export function doesn't export any of your password nor username.
