### ISSUE TITLE
OSD Overlay 4 is not placed on YX as expected

### ISSUE THREAD

**Issue by oxedgar** [Supergiovane/node-red-contrib-hikvision-ultimate#46]
Bonjour la communauté,

In the OSD text send node, we can enter 4 different texts on locations at the desired X and Y coordinates.

it works perfectly our first three texts but for the fourth, the location does not fix. it always appears at the top left of the image. and the value entered in the XY field of Node-Red is not saved. Value always returns empty without coordinates when opening text node config

**Describe the bug**

**Expected behavior**
Not any error message

**Hikvision-Ultimate Version**
 - lastest

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Comment by Supergiovane** [comment]
Hi
I’ll take a look. Can you paste here your flow, so i can check what happens?
Thanks.
