### ISSUE TITLE
event home_away

### ISSUE THREAD

**Issue by wifi75** [Supergiovane/node-red-contrib-hikvision-ultimate#47]
Hello why are armed at home and armed away event the same?
can you modify the code to have separate havings?

**Comment by Supergiovane** [comment]
Hi
I think you're referring to the AXPro node, right?
The node emits a property received from AxPro. If you inspect the msg, you should find the arming mode.

**Comment by wifi75** [comment]
Hi I'm using du Home assistant, and I need to have different states... I can't even find the entity actually.
I still don't understand where to find the status change
I need armed at home and armed away...

**Comment by wifi75** [comment]
@Supergiovane Supergiovane please see up

**Comment by wifi75** [comment]
Grazie mille, per la risposta, ma non so proprio come inserire quel codice.

**Comment by Supergiovane** [comment]
Prima di fare qualsiasi cosa, studia per bene node-red. Ci metti una giornata, ma ti renderai conto di come è facile e veloce poi gestire tutto quello che vuoi. Guarda i tutorial online e sul sito node-red.
