### ISSUE TITLE
help with a first run needed ;)

### ISSUE THREAD

**Issue by JacekKac** [Supergiovane/node-red-contrib-hikvision-ultimate#48]
hi there, is it possible to write a short manual how to run this node with minimal setup for AX pro. what i want to achieve is the ability to arm and disarm the ax pro device with a simply shell commands from linux or any other software. 

how can i achieve this to be done ? simple example how to start will be enought, i am not regular node-red user.

**Comment by Supergiovane** [comment]
Hi
This node works only in Node-Red, If you're using HomeAssistant, you can install Node-Red as HA plugin.
It's impossible to call any function of this node by a shell command, sorry.
