### ISSUE TITLE
AX PRO  not getting zone update message for second zone

### ISSUE THREAD

**Issue by JacekKac** [Supergiovane/node-red-contrib-hikvision-ultimate#49]
hi! i manage to run node-red with this library, connect to AX Pro, and setup a simply mqtt broker to send status / change setteings via mqtt commands. What is interesting for me

when i am playing with the APP hik connect or directly from node-red i see 

AXPRO {"zoneUpdate":{"id":0,"name":"Strefa przewodowa 1","status":"online","sensorStatus":"normal","tamperEvident":true,"shielded":false,"bypassed":false,"armed":true,"isArming":false,"alarm":false,"subSystemNo":1,"linkageSubSystem":[1],"detectorType":"passiveInfraredDetector","stayAway":false,"zoneType":"Instant","accessModuleType":"localTransmitter","moduleChannel":1,"zoneAttrib":"wired","deviceNo":2,"abnormalOrNot":false}}

when i send command to "whole alarm system" or to First zone (id number: 0). I have 2 zones in the setup and don't see any status updates for second zone even when i am playing with the zone from himkvision app. 

but i do see the CIDevents for different zones i think system 1 or 2 

"CIDEvent":{"code":3441,"name":"jkjebj","type":"armAndDisarm","trigger":"2023-03-13T13:59:00+01:00","upload":"2023-03-13T13:59:02+01:00","system":1,"subSystemName":"Dom parter"}}
AXPRO {"CIDEvent":{"code":1401,"name":"jkjebj","type":"armAndDisarm","trigger":"2023-03-13T14:00:30+01:00","upload":"2023-03-13T14:00:30+01:00","system":2,"subSystemName":"Dom pietro"}}
AXPRO {"CIDEvent":{"code":3401,"name":"jkjebj","type":"armAndDisarm","trigger":"2023-03-13T14:00:38+01:00","upload":"2023-03-13T14:00:38+01:00","system":2,"subSystemName":"Dom pietro"}}
AXPRO {"CIDEvent":{"code":3441,"name":"jkjebj","type":"armAndDisarm","trigger":"2023-03-13T14:00:39+01:00","upload":"2023-03-13T14:00:40+01:00","system":2,"subSystemName":"Dom pietro"}}

not sure if this is a bug we can fix, happy to help you with testing

**Comment by Supergiovane** [comment]
Hi
the arming works only if you have something to arm in the zone.
The Hik APIs reports only armed devices bellnging to a zone.
