### ISSUE TITLE
Connected but no alerts

### ISSUE THREAD

**Issue by JontyWeightman** [Supergiovane/node-red-contrib-hikvision-ultimate#5]
Hi, I've installed the package (1.0.25) and configured the node - they are reporting that they are connected to the NVR and I get get the model information back:
Name: Embedded Net DVR
Model: DS-7208HQHI-K1
Firmware: V4.30.101
But no alerts are received. The events are configured to sent to the Notification Centre and email address - they are displaying on the Hik-Connect app without issue - any ideas ?

**Comment by Supergiovane** [comment]
Hi
There is no need to set anything. 
If you’re using the alarm node, you just need to set the channel corresponding to your camera number set in the NVR. 
If you dont’t receive any alarm, should check wether your nvr has an option to enable ISAPI connections.

**Comment by JontyWeightman** [comment]
ISAPI is enabled - I have added a user to it but do do I need to add that user somewhere else as well?

The node is using the login details to the NVR.

Thanks

Jonathan

On 23 Jan 2021, at 17:36, Supergiovane <notifications@github.com> wrote:

﻿
Hi
There is no need to set anything.
If you’re using the alarm node, you just need to set the channel corresponding to your camera number set in the NVR.
If you dont’t receive any alarm, should check wether your nvr has an option to enable ISAPI connections.

**Comment by JontyWeightman** [comment]
Thanks for your help - I thought I would provide some screen shots in case I am missing something.


I presume the alarm IP host does not need to be set to anything?


HikVision:










Node Red:






But no messages out of the nodes when alerts are generated ?





On January 23, 2021 at 5:36 PM, Supergiovane <notifications@github.com> wrote:






Hi
There is no need to set anything.
If you’re using the alarm node, you just need to set the channel corresponding to your camera number set in the NVR.
If you dont’t receive any alarm, should check wether your nvr has an option to enable ISAPI connections.

**Comment by JontyWeightman** [comment]
One other thing - I have noticed the nodes move from "Waiting for Alarm" to "Connected" status - what's the difference?


They also seem to temporarily loose connection quite regularly - is this normal ? Both the raspberry pi and the NVR are connected to the same network switch.





On January 23, 2021 at 5:36 PM, Supergiovane <notifications@github.com> wrote:






Hi
There is no need to set anything.
If you’re using the alarm node, you just need to set the channel corresponding to your camera number set in the NVR.
If you dont’t receive any alarm, should check wether your nvr has an option to enable ISAPI connections.

**Comment by JontyWeightman** [comment]
To add - I have timed the loss of connection and it always happens at 40 seconds after connecting - what's the timing on the heartbeat ?


I have yesterday completely resest the NVR to factory default settings.


Sorry - no more emails now !!!


:-)

On January 23, 2021 at 6:19 PM, Jonathan Weightman <jonathanweightman@icloud.com> wrote:


One other thing - I have noticed the nodes move from "Waiting for Alarm" to "Connected" status - what's the difference?


They also seem to temporarily loose connection quite regularly - is this normal ? Both the raspberry pi and the NVR are connected to the same network switch.





On January 23, 2021 at 5:36 PM, Supergiovane <notifications@github.com> wrote:






Hi
There is no need to set anything.
If you’re using the alarm node, you just need to set the channel corresponding to your camera number set in the NVR.
If you dont’t receive any alarm, should check wether your nvr has an option to enable ISAPI connections.

**Comment by Supergiovane** [comment]
Hi
Please try to reply directly in gitHub, otherwise is a mess with the quoted text 😉
The NVR probably doesn’t relay the alarms. You need to connect the alarm node directly to the camera, instead of connecting it to the NVR. 
Disconnections should not appear in your case. Make sure to have the last node and nodered version. You can write node -v in a command line window, to check the node version. It should be 12.x or above, or better 14.x.

**Comment by JontyWeightman** [comment]
Thanks - I have misunderstood then, I thought it would pick up the events triggered in the NVR that are sent to the Hik-Connect app.


The cams are all co-ax not IP so sounds like it will not work - shame.


I'm running Node Red 20.5 but it still disconnects every 40 seconds.





On January 23, 2021 at 7:38 PM, Supergiovane <notifications@github.com> wrote:






Hi
Please try to reply directly in gitHub, otherwise is a mess with the quoted text 😉
The NVR probably doesn’t relay the alarms. You need to connect the alarm node directly to the camera, instead of connecting it to the NVR.
Disconnections should not appear in your case. Make sure to have the last node and nodered version. You can write node -v in a command line window, to check the node version. It should be 12.x or above, or better 14.x.

**Comment by Supergiovane** [comment]
Hi nodered 0.20.5 is very old. You should upgrade it and upgrade node.js as well. Then the disconnection will disappears. 
As for the Alarm notifications, i’ve no clue on how an analog nvr works, so i cannot help with that, but for me, if you upgrade node and nodered, you should be able to pick uo the events!

**Comment by JontyWeightman** [comment]
Thanks - I deleted the whole image on the raspberry pi and rebuilt with the latest version on Node Red and it fixed the issue.

Really appreciate your support.
