### ISSUE TITLE
ANPR problem

### ISSUE THREAD

**Issue by see3me** [Supergiovane/node-red-contrib-hikvision-ultimate#52]
We are using the the node-red-contrib-hikvision-ultimate for ANPR with: 
Name: IP CAMERA
Model: iDS-2CD7A26G0/P-IZHSY
Firmware__V5.8.20_230328_S3000489273

**Describe the bug**
<img width="947" alt="Bildschirm­foto 2023-05-25 um 10 34 41" src="https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/95181550/c6da67f3-7c61-4d01-a240-f39dfde86736">

Since the upgrade to Firmware__V5.8.20_230328_S3000489273 we get all 20s the error : Invalid header or no response

**To Reproduce**
comes every time

**Hikvision-Ultimate Version**
 - Eg. 1.1.95

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**

**Comment by see3me** [comment]
Hi,
witch ports do you need?
Then I will start with the prot forwarding
Yours Alex

Am Do., 25. Mai 2023 um 11:36 Uhr schrieb Massimo Saccani <
***@***.***>:

**Comment by Supergiovane** [comment]
Hi
Any port you want, is ok for me.

**Comment by see3me** [comment]
Hi,

https://share.1password.com/s#zvGJiAp9nqOUlp2aMNB6aYoV2nPV4jg1ChGL11IsfRg

I have set you a own user, is forwarded
LG

Am Do., 25. Mai 2023 um 11:58 Uhr schrieb Massimo Saccani <
***@***.***>:

**Comment by Supergiovane** [comment]
Thank you.
Leave me please some time to investigate...

**Comment by Supergiovane** [comment]
Hi
V. 1.1.10 is out.
I've tried to mitigate the issue, but i've discovered, that sometimes, the camera simply drops the connection without reasons.
Anyway, even if it drops the connection, the node will reconnect and re-read the "losts" plates that the camera captured during the offline time.
Please try it and let me know!
Thanks.
