### ISSUE TITLE
[Question] Face recognition Terminals

### ISSUE THREAD

**Issue by dudu631** [Supergiovane/node-red-contrib-hikvision-ultimate#55]
Hey!

Do you know if this will work with any of the face recognition access control terminals? 

If not, do you have plans to listen to the events of those terminals?

Thank you!

**Comment by Supergiovane** [comment]
Hi dudu.
You can try using the RAW node, to receive the events.
I haven't any recognition access contro terminal to develop a specific node.
I've developed the nodes starting from a physical device, by learning their ISAPI.
So for now, no, i've no plans to buy a recognition access contro terminal.
