### ISSUE TITLE
Hikvision-config: FETCH ERROR: The user aborted a request.

### ISSUE THREAD

**Issue by TheBartoMan** [Supergiovane/node-red-contrib-hikvision-ultimate#56]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hello, Please can you help?

**Describe the bug**
I keep getting loads of errors contantly in my debug log.

Hikvision-config: FETCH ERROR: The user aborted a request.
Hikvision-config: streamPipeline: The user aborted a request.http://192.168.1.216:80

Everything seems to be working, and i dont see any errors on my nodes.

Can I please ask, does Hikvision-Ultimate not make use of the Catch error feature in Node-Red?

All other modules i have that create errors are picked up my the Catch so I can address them.

The errors I get from Hikvision-Ultimate dont point to any specific module and I cant find a way to address the hundred of errors.

**To Reproduce**
I can list any way to reproduce, its just happens constantly.

**Expected behavior**
Not recieved the errors, or at least have a better way to find the cause and to deal with the errors

**Screenshots**
![CleanShot 2023-10-10 at 09 38 05@2x](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/28529964/883b4467-4c0b-43bd-b03c-78100077653c)

**Hikvision-Ultimate Version**
1.1.11

**Are you running node-red behind homematic, docker or anything similar?**
No

**Additional context**

**Comment by Supergiovane** [comment]
node-red-contrib-hikvision-ultimate@1.1.12 is out with silenced log.

**Comment by TheBartoMan** [comment]
What does "silenced log" mean? Will the errors still be accessible somewhere? Would be good to see the genuine ones.

**Comment by Supergiovane** [comment]
Hi
The error is still there, but is not logged anymore, until you put a banana behind the IP, in the camera config window.
For example, if the camera IP is 192.168.1.216, add a banana like this **192.168.1.216banana**
You'll see the full debug logs.

**Comment by TheBartoMan** [comment]
What kind of coding is that? Adding banana at the end?!

Can you not output to the catch logs so we can catch the events and deal with them accordingly?

Have you just removed some errors or all errors? How we meant to know when we have a genuine problem please?

I still dont know it the issue i reported was a genuine problem i was getting? and what was causing it?

**Comment by Supergiovane** [comment]
Hi
feel free to do the changes by yourself and send me a PR.
