### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by pmattia90** [Supergiovane/node-red-contrib-hikvision-ultimate#58]
Ciao Supergiovane,
uso il tuo Hikvision-ultimate da tempo e ho spulciato il codice per capirci qualcosa più a fondo.
Ho individuato un paio di TYPO, che potrebbe farti piacere sistemare.
Nel frattempo molte grazie per la condivisione del tuo lavoro.
in HikvisionUltimateAlarm.html
Main "voltge" supply 
"Bulgary" alarm

**Comment by Supergiovane** [comment]
Ciao! Mattia
grazie mille, li modifico immediatamente!

**Comment by Supergiovane** [comment]
node-red-contrib-hikvision-ultimate@1.1.14 è stata pubblicata.
