### ISSUE TITLE
iDS-7616NXI-I2/X(C) no notification face recognition

### ISSUE THREAD

**Issue by semikor** [Supergiovane/node-red-contrib-hikvision-ultimate#60]
Hello!
Thank you so much for your work and wonderful application!
Device Model: iDS-7616NXI-I2 / X
Firmware Version: V4.62.210 build 230619
Encoding Version: V5.0 build 230530
Hardware Version: 0100000091010000
FR Version: V6.2.0
Perimeter Protection Algorithm Version: V2.1.0
HMS Version: V4.8.1
Version of Face Capture Algorithm Library: V6.2.0
Object Thrown from Building Detection Version: V1.1.0
Web Version: V4.5.0 build 20230524
Plug-In Version: V3.0.8.32

![Снимок экрана 2024-02-09 195557](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/68992298/7a0583e3-d5e5-4b8a-aad8-f49b29a3ade2)

Unfortunately, I can’t get a notification from NVR about a face recognition event. 
On Hik-Connect they are coming.
Actually NVR works.
Notifications are sent by email.

Event Motion Detection - come to node-red

Thank you!

**Comment by Supergiovane** [comment]
Hi
Many of these “special” events aren’t routed to the ISAPI, they are routed via SDK. 
I haven’t any NVR or camera capable of face recognition, so i cannot try to reproduce the issue, but you could try using the RAW event node. That node may work for you.

**Comment by semikor** [comment]
Yes, I use node RAW.
Very, very sorry (((
I was counting specifically on a notification about a recognized face, which would be used further in automation...

**Comment by Supergiovane** [comment]
You could try installing home assistant. I know there is an sdk implementation. Give it a try!

**Comment by semikor** [comment]
Yes, I have Home Assistant.
What kind of integration should you look for?
Can’t you get it through SNMP?

**Comment by Supergiovane** [comment]
The standard hikvision integration should be fine. I don’t remember yet, what i had installed.

**Comment by semikor** [comment]
https://www.home-assistant.io/integrations/hikvision
This?
I connected it, but there was nothing except Motion (((

**Comment by semikor** [comment]
![Снимок экрана 2024-02-09 211122](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/68992298/e86bc71a-df9c-4769-994d-64cecb12a814)

**Comment by Supergiovane** [comment]
Search for “pergola.fabio” in the HA forum. 
I’ve had a beautiful conversation with that guy and i know, it has used SDK. 
https://community.home-assistant.io/t/hilvision-callsignal/611749/2

**Comment by semikor** [comment]
Thank you very much!
I'll try to dig around...

**Comment by semikor** [comment]
> Search for “pergola.fabio” in the HA forum. I’ve had a beautiful conversation with that guy and i know, it has used SDK. https://community.home-assistant.io/t/hilvision-callsignal/611749/2

Oops! That page doesn’t exist or is private.
(((

**Comment by Supergiovane** [comment]
Hmm… you should see it if you’re a registered user.

**Comment by semikor** [comment]
Yes, he's registered, but he doesn't want to show it.
