### ISSUE TITLE
eventState: "inactive"?

### ISSUE THREAD

**Issue by semikor** [Supergiovane/node-red-contrib-hikvision-ultimate#62]
Hello!
Please tell me!
The RAW Camera Event node always returns only eventState: "active".
Why don't I receive eventState: "inactive" messages when the event ends?
Thank you!

**Comment by Supergiovane** [comment]
Hi
there is no "inactive" events on motion detection ISAPI.

**Comment by semikor** [comment]
do I need to set a timer at the output of the node?

**Comment by Supergiovane** [comment]
Depending on what you need to achieve, yes.
