### ISSUE TITLE
Filtration time in camera event

### ISSUE THREAD

**Issue by Luca27884** [Supergiovane/node-red-contrib-hikvision-ultimate#63]
Hello, thanks very much for you job!

I've seen in your code of camera event ad raw camera event there are two filtration time, but i can't see them when i program the node inside node red.

Hikvision-Ultimate version:
1.1.14

Node red is running inside Home Assistant Supervised in mini pc.

![camera event node](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/136231951/bed1271d-ed3d-41a0-8f68-37950005c343)

thanks again for your support.

**Comment by Supergiovane** [comment]
Hi
Please point me out, where the timers are

**Comment by Luca27884** [comment]
![filtro allarme](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/136231951/ed7755f9-0d14-4629-aac7-8b81611dc462)

![nascondi filtro](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/136231951/2bf7c69a-902c-4fdf-a3c2-ad14c8ff397c)


this filter that you hide with camera function.
why do you hyde in that situation?

it could be very usefull when you use camera motion control to avoid too many false alarm.

thanks again! very kind

**Comment by Supergiovane** [comment]
Hi
this set of timer is specific for radars.
In case of cameras or NVR, the filtering time should be set directly into the camera/NVR.

**Comment by Luca27884** [comment]
hello.

I apologize.
Very very very kind!

Thanks
