### ISSUE TITLE
ANPR - Repeating Old Plates

### ISSUE THREAD

**Issue by jpgnz** [Supergiovane/node-red-contrib-hikvision-ultimate#67]
Good Evening!

I've just stumbled across this add-on while trying to build this manually in NodeRED, great find! I've been able to immediately connect my camera and it is reading plates, however it seems to be constantly repeating the last plate that went past the camera.

**To Reproduce**
1. Added add-on as per instructions
2. When I added the camera, deployed and reloaded page
3. ANPR Node connects, but then cycles through the previous plate, see screenshots:

**Expected behavior**
Doesn't repeat.

**Screenshots**
1
![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/af1b76d0-1135-460e-8df0-141f4bf554dc)

2
![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/964fa2b4-f49a-45b5-b49b-efb8fdf8e1bd)

3
![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/a4f5e2c9-f87a-49db-92a2-8af2c5cf625a)

4
![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/a57c35ac-c3f4-4f1e-99b1-b5acb1fbee6b)

Then, go back to 3 after 20 seconds (default) and repeat.

![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/fa795eba-4bc5-4a2e-8d36-da957ea24bdb)

node-red-contrib-hikvision-ultimate 1.1.16
Node-RED 17.0.11
Core 2024.4.0
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240403.1

Camera iDS-2CD7A46G0/P-IZHSY

**Comment by Supergiovane** [comment]
Hi
Great camera the iDS-2CD7A46G0/P-IZHSY, i wish to have one also.

The camera repeats the plate while the car is passing, so the node is filtering the multiple reads.

**Comment by jpgnz** [comment]
Hey thanks for your quick reply! Currently, there is no vehicle passing the site at all, that vehicle passed the camera at 5:46pm, but the node keeps outputting:

![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/259adc68-85b7-44b0-8066-3b0a6e706b93)

**Comment by Supergiovane** [comment]
Hi
it could be either a new firmware behaviour (i've an older anpr camera to test with), or a different datetime format.
The camera records a list of plates and puts the last seen plate on the top of that list. The node must pull this list (there is no other way) and filter by either datetime and file number (the file is the screenshot of the plate).
Can you check the datetime format on the camera and assure, that is the same format as your node-red machine?

**Comment by jpgnz** [comment]
Ok understood.

NodeRed is running as a HomeAssistant Addon. HomeAssistant has the correct time, as does NodeRed. The camera itself is also correct, everything synced to same NTP server.

Is this the format you expect?

```bash
curl -X POST "http://camera.ip:80/ISAPI/Traffic/channels/1/vehicleDetect/plates" \
     -H "Content-Type: application/xml" \
     --data-raw "<AfterTime><picTime></picTime></AfterTime>" \
     --max-redirs 20 \
     --max-time 5 \
     --location \
     --digest \
     -u "login:pass"
	 
```
	 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Plates version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<snipped>
<Plate>
<captureTime>20240416T174516+1200</captureTime>
<plateNumber>DSF234</plateNumber>
<picName>202404161745168960</picName>
<country>ATN</country>
<laneNo>1</laneNo>
<direction>reverse</direction>
<matchingResult>otherlist</matchingResult>
</Plate>
<Plate>
<captureTime>20240416T174653+1200</captureTime>
<plateNumber>PME521</plateNumber>
<picName>202404161746538570</picName>
<country>ATN</country>
<laneNo>1</laneNo>
<direction>reverse</direction>
<matchingResult>otherlist</matchingResult>
</Plate>
</Plates>
```

**Comment by Supergiovane** [comment]
Hi
yes, is that was i'm expecting.
Let me test your XML, because my camera uses xml api schema version 1.0, while yours the 2.0.
I revert to you asap...

**Comment by Supergiovane** [comment]
Hi,
are you able to replace a file into home assistant's node-red installation? If yes, please find **ANPR-config.js** and replace it with the content of this zip, then restart node-red.
If you're unable, i'll publish an update, but it will take some time to show up in the node-red palettes.

[ANPR-config.js.zip](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/14994781/ANPR-config.js.zip)

**Comment by jpgnz** [comment]
Hey @Supergiovane - I have SSH access, easier for me to just manually modify the file, which I've done, and it looks to be resolved:

![image](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/assets/1733900/e4821147-2261-4513-9393-a95ea1f87e99)

Now I just need to wait for a vehicle... :) Thanks.

**Comment by Supergiovane** [comment]
You're wellcome and thank you to you for providing me the XML!!

**Comment by Supergiovane** [comment]
You're wellcome! :-)

**Comment by jpgnz** [comment]
Can confirm, lots of traffic today, fix worked as expected, thanks!

**Comment by Supergiovane** [comment]
Thanks to you for the feedback.
