### ISSUE TITLE
Audio Output - Camera

### ISSUE THREAD

**Issue by JS-DE-Tech** [Supergiovane/node-red-contrib-hikvision-ultimate#68]
First of all, thank you for this absolutely brilliant implementation for node red.

Iám using some Hikvision DS-2CD2686G2-IZSU/SL cameras and would like to use them to signal a possible break-in. I was hoping to be able to control this with the new speaker extension. Is there any way to playback the WAVE files loaded onto the camera via node red? The playback should take place independently of a camera event.

**Comment by Supergiovane** [comment]
Hi
Currently no. You can only play the files loaded into the speaker.
