### ISSUE TITLE
question rather than bug - AX PRO integration - hikconnect notification constantly popping up 

### ISSUE THREAD

**Issue by JacekKac** [Supergiovane/node-red-contrib-hikvision-ultimate#69]
In newer ax pro fimware user (administrator) is receving hik-connect notification every time the integration log-in using Installer login/passwd. 
Is there a way to get rid of this ? can i use other than installer account to get the status info and arm disarm (i am assuming the admin has the right access.

**Comment by Supergiovane** [comment]
Hi
You should ask this in an ax-pro forum.
I know you can disable this notification, but i don’t remember if i’ve done it in the ax-pro  or in the phone app.
