### ISSUE TITLE
Feature request: text overlay node

### ISSUE THREAD

**Issue by xury77** [Supergiovane/node-red-contrib-hikvision-ultimate#7]
Hi. Supergiovane.
It would be nice to have a text overlay node using Hikvision ISAPI
I use following flow to show temperature on video stream:
[textoverlay.txt](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/5883608/textoverlay.txt)
Unfortunately, I don't have the skills to make  a node.
I don't think it would be a problem for you.

**Comment by Supergiovane** [comment]
Hi,
will take a look for the next releases.

**Comment by Supergiovane** [comment]
Hi
v.1.0.27 is out with a simple text overlay. For more advanced one, you can use any other node-red image manipulation node.

**Comment by xury77** [comment]
Thanks. Its works fine, but my intention was use Hikvision ISAPI  text overlay to lay text overlay visible on live stream, and recorded to DVR/NVR device.  Same way as cooperation with POS device. However using with dashboard is also cool feature.

**Comment by Supergiovane** [comment]
Hi
ISAPI docs are very very poorly documented, so for now i opted for a simpler way.

**Comment by Supergiovane** [comment]
Hi xury77
a textoverlay node with ISAPI will be out today with 1.0.28

**Comment by xury77** [comment]
Hi Supergiovane. 
Unfortunately, it does not work for me, but I expected it, because the xml format  for my DVR is probably  slightly different from most hikvision IP cameras.
I have a cheap TurboHD DVR DS-7104HGHI-F1.
But I'll check on other cameras.
My error is:
client.Generic.Request.Fetch.Error: Error Response: Bad request(29,21.33.14)
I suppose you used the shortened xml. as described below:
https://www.iotwithus.com/hikvision-and-text-overlay/
The example from the first post in textoverlay.txt works for me.
Nevertheless, I appreciate your work and thank you for that.

**Comment by Supergiovane** [comment]
Hi
If you change che channel by hand in the url, does it works?

**Comment by Supergiovane** [comment]
V. 1.0.29 is out. It should work for you as well.
