### ISSUE TITLE
Access Properties of the Node

### ISSUE THREAD

**Issue by Harvey-Mushman** [Supergiovane/node-red-contrib-hikvision-ultimate#72]
Hello Massimo Saccani

**Describe the bug**

Not a bug but after sending you a request through Paypal, the response you gave was to post my questions here.

1. The status is displayed below the "Ovest" node in the sample flow.  I would like to access this status and return it to the dashboard so the user has an idea of what is going on in the background.  Where can this property be retrieved?

2. In the debug window of Node-Red, I see the BANANA PROCESSING object getting refreshed continually, I assume this is normal behavior but wonder if there is a way to stop it when the camera is not in use by my application?

3. Is it possible to see the live video stream?

4. The camera I'm currently testing with has audio input, output and alarm capabilities.  It is not clear how to access these features from my Node-Red application that is running on a Raspberry Pi.  Once my application is finished, I would like to have two-way conversations from my browser to the camera.  The application is a doorbell/access control project where I'm assuming hte camera alarm will trigger an MQTT notification at which point the user will visit a webpage that has audio out, a push to talk button to control the mic and if access is ok, the alarm output will release a magnetic door lock.

Any response to these four questions would be greatly appreciated.

Best,
Harvey

**Comment by Supergiovane** [comment]
Hi
1. There is a “status” node, that grabs the status of other nodes. It’s a node shipped with node-red 👍🏻
2. Check wether near the camera’s IP address (in the node configuration) there is a “banana”. If yes, yes remove it. It’s a command to log all things. 
3. No. I suggest you not to do so via node-red. Rather, if exists, use a dashboard image node and link it to the camera stream directly. It’s pretty easy and you won’t overload your raspberry. 
4. It’s nearly impossible to do. Hikvision hasn’t released an ISAPI that allow to do so. I’ve struggled a lot, with the help of some Homeassistant devs, without success. I ended up attaching a shelly input to the alarm output of my Hikvision doorbell and catch the event via the shelly node.
