### ISSUE TITLE
Hikvision DS-KV6113-WPE1(C) V2.2.77 - {msg.hangUp=true} it doesn't work

### ISSUE THREAD

**Issue by semikor** [Supergiovane/node-red-contrib-hikvision-ultimate#73]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Greetings!
Let me express my gratitude for your hard work and invaluable contribution!

**Describe the bug**
Node Doorbell
Hikvision DS-KV6113-WPE1(C) on the version V2.2.77 build 240515
https://www.hikvision.com/ca-en/products/Video-Intercom-Products/IP-Series/Pro-Series/ds-kv6113-wpe1-c-/
it stopped working msg.hangUp=true - returns an error:
"hikvisionUltimateDoorbell: Error reject clientGenericRequest.fetch error:Error response: Bad Request"
On the previous version V2.2.65 - everything worked as it should.
msg.openDoor=1 - It still works great.

**Hikvision-Ultimate Version**
 - 1.1.22

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red works on a VM (2CPU 4GB) Synology 923+ 

**Additional context**
All other node Doorbell functions work as stated.

**Comment by Supergiovane** [comment]
Hi
yes, this is an unfixable issue, because Hikvision has dropped the hangup support via ISAPI.
Mine also doesn't work anymore!!
I've tried also a plugin for Home Assistant (made with SDK instead of ISAPI) and also that plugin doesn't hang up the call.
Sorry.

**Comment by semikor** [comment]
Do you know if it is possible to roll back the panel firmware to the previous 2.2.65?

**Comment by Supergiovane** [comment]
Here https://www.hikvisioneurope.com/eu/portal/?dir=portal/Technical%20Materials there are some of the firmware. Maybe you can check here.

**Comment by semikor** [comment]
I have the firmware itself.
I meant is it safe for the panel? Won't the panel turn into a brick? Is it possible to upgrade to the previous firmware via the web interface?
I've never done this with a Hik... ))

**Comment by Supergiovane** [comment]
I've done a downgrade once. The device was nearly bricked, but i was able to restore it to factory default.
It's dangerous to downgrade.

I'm working on a way to use a shelly actuator device to physically "push" the hangup button on the indoor station.

**Comment by semikor** [comment]
I see, thanks!

**Comment by semikor** [comment]
> I'm working on a way to use a shelly actuator device to physically "push" the hangup button on the indoor station.

What monitor do you have? Or are you talking about the call panel?
I have Hikvision DS-KH9510-WTE 1(B) on Android. I don't understand how to use it... A bunch of external inputs, but almost all of them are not used in any way (((

**Comment by Supergiovane** [comment]
Hi, 
i also have DS-KH9510-WTE 1(B). The Hangup button is only on the touch screen interface. I found no suitable input nor can i hack the main board. I'm exploring other ways...

**Comment by semikor** [comment]
Won't Macrodroid be able to help? It works fine on a smartphone ))

**Comment by Supergiovane** [comment]
I want a more "stable" solution over time.

**Comment by semikor** [comment]
Yes, it's understandable.
Thank you very much!

**Comment by semikor** [comment]
I made a downgrade DS-KV6113-WPE1(C) to v2.2.65, but the hangUp did not work ((
What version does hangUp run on?
Or does it not depend on the firmware of the panel?
It seems to me that it used to work on v2.65...

**Comment by Supergiovane** [comment]
Hi
i don't know, sorry. I'm working on a definitive "hardware" solution, independent from all currently and future firmwares.

**Comment by Supergiovane** [comment]
Try with home assistant, maybe the v2.2.65 works with it.

**Comment by semikor** [comment]
> Hi i don't know, sorry. I'm working on a definitive "hardware" solution, independent from all currently and future firmwares.

Will you share it?))

**Comment by semikor** [comment]
> Try with home assistant, maybe the v2.2.65 works with it.

And how is it in HA? I'm not really friends with him...
make a script with hangUp=true?

**Comment by Supergiovane** [comment]
> > Hi i don't know, sorry. I'm working on a definitive "hardware" solution, independent from all currently and future firmwares.
> 
> Will you share it?))

As soon as i find a solution, yes. But it take time.

**Comment by Supergiovane** [comment]
> > Try with home assistant, maybe the v2.2.65 works with it.
> 
> And how is it in HA? I'm not really friends with him... make a script with hangUp=true?

No, in HA you must install a plugin. https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell/README.md

I've used it in the past, but after an upgrade of Home Assistant, it broke.

**Comment by semikor** [comment]
> > > Try with home assistant, maybe the v2.2.65 works with it.
> > 
> > 
> > And how is it in HA? I'm not really friends with him... make a script with hangUp=true?
> 
> No, in HA you must install a plugin. https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell/README.md
> 
> I've used it in the past, but after an upgrade of Home Assistant, it broke.

installed, configured...
no, it doesn't work either (((
