### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by namihaus** [Supergiovane/node-red-contrib-hikvision-ultimate#74]
Hi,

Sometimes the connection to a Hikvision DS-2TD1217-2/QA camera, for example via a camera event, does not work for a certain period of time. The node displays **"403 Forbidden"**, and the debug error message shows the following:
**"Hikvision-config: FETCH ERROR: StatusResponse Forbidden".**

I reviewed some of the code, and the endpoint being called that causes this issue is in the file _Hikvision-config.js_ at line 208 (_/ISAPI/Event/notification/alertStream_).

When I tried to call the endpoint manually, I received this error:

```
<?xml version="1.0" encoding="UTF-8"?>  
<ResponseStatus version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">  
  <requestURL></requestURL>  
  <statusCode>4</statusCode>  
  <statusString>Invalid Operation</statusString>  
  <subStatusCode>invalidOperation</subStatusCode>  
</ResponseStatus>
```

After some troubleshooting, I discovered that each endpoint has its own connection limit (other endpoints are working). SSHing into the camera and running `netstat` revealed that the server where my Node-RED instance is running has about 18 connections to the camera, most of which are in TIME_WAIT status, with only one showing as ESTABLISHED.

It seems that the Hikvision-ultimate node is opening too many connections and not closing them properly. According to the Hikvision API documentation found [here](https://enpinfo.hikvision.com/unzip/20210507165058_24612_doc/GUID-C8398309-7417-4540-AF4F-4DA909E766D2.html), it states:

> "After calling this URI, a persistent connection is set up between the device and the platform, and the alarm or event information will be uploaded continuously once the alarm is triggered or an event occurs."

Could it be that the endpoint is being called incorrectly? (I'm not an expert in this area).

As for why the connections are accumulating, I suspect it may be because I am deploying my Node-RED flows too frequently or too quickly while experimenting.

If you need any more information or assistance in resolving this issue, feel free to contact me :)

**Comment by namihaus** [comment]
Hi,
cool that you are still active :D

I just tested again and if you quickly press deploy (try to toggle a debug node on and off in between to enable the deploy button) it will create a few connections and lead to the issue (at least on my camera model).
`netstat` then shows the connections with "TIME_WAIT".

I also reviewed your code, to find out where the connections should be closed and it seems like you are already doing that in the correct way by using a abort controller and _calling controller.abort()_ in the close hook of the node.

But the package "[digest-fetch](https://www.npmjs.com/package/digest-fetch)" you are using does not seem to have a field "signal" in the options options, so passing _controller.signal_ will not do anything :(

Did you previously use another package?

**Comment by Supergiovane** [comment]
Hi
Digest-fetch wraps up the fetch package and it should have signals. 
Anyway, if you look at the Ax Pro node, you’ll see that i’ve adopted another way to get the alertstream. I had plans to swap digest-fetch with eventsource, but i’ve been (and i’m also yet) busy with other my nodes. And, hey, i’m always active (at least until i die 🤔)

**Comment by Supergiovane** [comment]
Hi
Can you unzip this file into your **.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes** folder and restart node-red? I've switched the abort controller to the native one (you must have nodejs v14.17.x or above), and set a wait of 1 sec after aborting, to avoid a too fast reinstantiation of the alert stream reader.

[Archivio.zip](https://github.com/user-attachments/files/17964888/Archivio.zip)

**Comment by Supergiovane** [comment]
If you still find time_waits, i'll try to reuse the pendant connection using keepAlive.

**Comment by Supergiovane** [comment]
PS: ...and this is the file with the keepalive and maxconnection set to 1, with both http and https.

[Hikvision-config.js.zip](https://github.com/user-attachments/files/17965025/Hikvision-config.js.zip)

Please try this also and let me know. My netstat show now no TIME_WAIT for Mac.localdomain (my developer machine used for testing)

`
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0    112 192.168.1.60:22         Mac.localdomain:60376   ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:8000 ::ffff:192.168.1.32:42880 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:554 ::ffff:192.168.1.32:51707 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:8000 ::ffff:192.168.1.11:50176 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33886 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:554 ::ffff:192.168.1.32:51906 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:554 ::ffff:192.168.1.32:51904 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:554 xeoma.saccani.it:56556  ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:554 ::ffff:192.168.1.32:51709 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33888 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:http xeoma.saccani.it:56558  ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33884 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33882 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:http Mac.localdomain:62074   ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:8000 ::ffff:192.168.1.32:42879 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33890 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:http ::ffff:192.168.1.16:53138 ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:http unifi.localdomain:33892 TIME_WAIT   
tcp        0      0 ::ffff:192.168.1.60:554 xeoma.saccani.it:56557  ESTABLISHED 
tcp        0      0 ::ffff:192.168.1.60:8000 ::ffff:192.168.1.32:43097 ESTABLISHED 

`

**Comment by namihaus** [comment]
Hi,
I have Home Assistant running, and I am using the Node-RED add-on. It's really difficult to access the filesystem because Node-RED runs in a Docker container, and Home Assistant strips away most of the CLI functionality and also seems to hide the containers.
Would it be possible for you to provide me with a packaged tar.gz bundle (preferably with a separate bundle identifier), so I can just upload it to Node-RED?
Sorry for the trouble, but I spent about half an hour trying to access Node-RED's filesystem and failed. :(

**Comment by Supergiovane** [comment]
Hi
I’ll publish a new release in about 30 minutes. Nust update as usual.

**Comment by namihaus** [comment]
Hi,
Thank you for your efforts! Sorry that I was unable to test it today.
I will try it tomorrow and test your changes :)

**Comment by namihaus** [comment]
Hi,
I just updated to 1.2.2, but it does not seem to resolve the issue. This is my netstat after like 6 deploys:


# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0    300 192.168.0.53:22         PC-PF4ZJP2P.localdomain:58205 ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51674     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51604     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51664     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51644     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51610     ESTABLISHED
tcp   1733940      0 ::ffff:192.168.0.53:http ::ffff:192.168.0.99:47068 ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:33112     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:554 ::ffff:192.168.0.99:33676 ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51632     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:35186     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51654     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http ::ffff:192.168.0.99:47070 ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:33128     ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:35198     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:33132     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:51626     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:53686     TIME_WAIT
tcp        0      0 ::ffff:192.168.0.53:http ::ffff:192.168.0.99:47076 ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http homeassistant:33140     ESTABLISHED
tcp        0      0 ::ffff:192.168.0.53:http ::ffff:192.168.0.99:47164 ESTABLISHED

**Comment by Supergiovane** [comment]
Hi
Do you run HASSIO? Aka is Homeassistant dockerized?

**Comment by Supergiovane** [comment]
Hi
No no, don't worry!
I'm installing HA now.... i'll let you know.

**Comment by namihaus** [comment]
Any news? If you need me to install node red, I can do that ;)

**Comment by Supergiovane** [comment]
Hi
i have max 1 TIME_WAIT from hikvision node.
I'm testing with  DS-2TD2628-3/QA and DS-2TD1228-2/QA. Using NR with HA is fine.
The DS-2TD1217-2/QA should have less pixels, but it should be the same.
Do you have installed the latest firmware for your cam [from here](https://www.hikvision.com/en/support/download/firmware/)?

![Firmware_-_Download_-_Hikvision](https://github.com/user-attachments/assets/d23d77ac-ad07-4352-a603-ba2e54c5d127)

**Comment by namihaus** [comment]
Hi,
I updated to the latest version as soon as I noticed the issue, so yes, it is up to date.
V5.5.98 build 240726 is currently installed.


In will try to replicate the issue with a small js script to check if it is a camera issue.

**Comment by namihaus** [comment]
I tested it yesterday and found that if I deploy in a normal manner (like every minute or so), the connections are no longer accumulating. However, as soon as I deploy more quickly (e.g. every 3 seconds), the issue reappears. Since this is not a typical use case, I would say we can close the issue, as the normal use case is now working.

Thank you for fixing the issue! :)
