### ISSUE TITLE
the Picture node stopped working on 1.2.2.

### ISSUE THREAD

**Issue by semikor** [Supergiovane/node-red-contrib-hikvision-ultimate#75]
Greetings!
Updated node-red-contrib-hikvision-ultimate to 1.2.2 and all Picture nodes stopped working. It worked on the previous version.

![Снимок экрана 2024-12-02 155835](https://github.com/user-attachments/assets/dd68f059-03f8-447d-aec0-1bc71a02cbb7)

**Comment by Supergiovane** [comment]
Hi
Please revert to 1.2.1

**Comment by semikor** [comment]
Yes, well, thank you!

**Comment by semikor** [comment]
> Yes. You should see it in about 20 minutes.

Updated to 1.2.3
Works.
Thank you very much!!!!
