### ISSUE TITLE
Does not work "openDoor=1" on the version 1.2.2 and 1.2.3

### ISSUE THREAD

**Issue by semikor** [Supergiovane/node-red-contrib-hikvision-ultimate#76]
Greetings!
I noticed that after the update node-red-contrib-hikvision-ultimate to the version 1.2.2 and 1.2.3 the team stopped working "msg.openDoor = 1" (and even earlier "msg.hangUp = true") and it's not related to firmware Hikvision DS-KV6113-WPE1(C).
Tested on versions:
V2.2.53 build 230918
V2.2.65 build 231213
V2.2.77 build 240515
V2.2.78 build 241012

**Comment by Supergiovane** [comment]
Hi
it should be fixed in 1.2.4
Please try it and let me know. Thanks.

**Comment by semikor** [comment]
> Hi it should be fixed in 1.2.4 Please try it and let me know. Thanks.

Well, thanks!
There is no 1.2.4 in the palette yet...

**Comment by semikor** [comment]
> Hi it should be fixed in 1.2.4 Please try it and let me know. Thanks.

Thanks!
I updated it to 1.2.4 and the "msg.openDoor = 1" is working again.
