### ISSUE TITLE
BANANA ERRORE fast-xml-parser

### ISSUE THREAD

**Issue by JonasLTU** [Supergiovane/node-red-contrib-hikvision-ultimate#78]
Hi everyone, 
The plugin seems to function and interact with the relays of the door station, but I get frequent errors in Node Red debug window.

**Describe the bug**
Frequent errors appearing in Node Red Debug window:
BANANA ERRORE fast-xml-parser(sRet, function (err, result) Unexpected non-whitespace character after JSON at position 402"
Any ideas what could be causing this?

**Hikvision-Ultimate Version**
 - Latest 1.2.4 on Node Red 4.0.5

Door station Hikvision DS-KV9503-WBE1 with latest V2.3.13 build 241026 firmware.

![image](https://github.com/user-attachments/assets/ab7a79ec-dee5-4437-82ff-fbf5760a1d18)

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red in Docker on a Ubuntu powered PC

**Comment by JonasLTU** [comment]
Amazing! Thanks a lot!

**Comment by Supergiovane** [comment]
Hi
i think you can disable these messages, by going into the config window and select no debug, like there:

![Node-RED___Sensori_antifurto](https://github.com/user-attachments/assets/36fbd9dc-5caf-4fda-b5f7-872718e8e095)

**Comment by Supergiovane** [comment]
node-red-contrib-hikvision-ultimate@1.2.5 is out, you should see it in about 20 minutes.

**Comment by JonasLTU** [comment]
There is no such option id the Doorbell node config:
![image](https://github.com/user-attachments/assets/58937938-9455-4b7c-9c70-59ca08a11ded)

Thansk @Supergiovane  - will check the new version later today!

**Comment by JonasLTU** [comment]
It seems the error is still coming up with the new version.

**Comment by Supergiovane** [comment]
Can you show me your flow (screenshot) and also export and paste here the doorbell node (using the "export" function of node-red)?

**Comment by Supergiovane** [comment]
I mean, the **doorbel node config** (where you set the IP etc).

**Comment by JonasLTU** [comment]
I tried to recreate the doorbell-server config node with the new version, and it seems the errors are not coming any more. Will have to test functionality tomorrow. Of note, this "Doorbell config node" does not seem to have Debug settings.

**Comment by Supergiovane** [comment]
Hi
Yes, i need to add the “debug” option on that ;-)
