### ISSUE TITLE
Text Overlay Size

### ISSUE THREAD

**Issue by Deggle** [Supergiovane/node-red-contrib-hikvision-ultimate#8]
This is a really useful node so thank you so much for your work.

One issue I've found is that when posting a text overlay the set font size is overridden to the smallest. On my setup this is too small to be useful so I'm not really able to use this feature.

I think it would be helpful if the sizes (for me 16x16, 32x32, 64x64) could be specified in the node as I assume this must already be being in the data posted (or perhaps it's not and DVRs that support multiple sizes are defaulting to [0] which is 16x16)?

There is also a setting for flashing and/or transparent text which would be pretty useful if it could be added.

Settings on my DVR, per camera:
![image](https://user-images.githubusercontent.com/6651579/106353084-ebe7d400-62df-11eb-92f1-1964fca37de0.png)

**Comment by Supergiovane** [comment]
Hi Deggle
the ISAPI documentation doesn't even mention the font size, so i must dig into the internet and find a way to do this.
I'll take a look.

**Comment by Deggle** [comment]
Thanks for taking the time to look into it. Let me know if I can do anything to help.

I'm not sure if the element names in the web GUI align with the ISAPI info, but in case it's useful:
![image](https://user-images.githubusercontent.com/6651579/106353712-6e729280-62e4-11eb-8b35-5af25b4e31c0.png)

**Comment by Supergiovane** [comment]
Mmm... yes and no, but thank you anyway... i maybe found an old API document mentioning this.
Stay tuned. If possible, i'll push a new version already today.

**Comment by Supergiovane** [comment]
Sorry for the delay
i had to fix some issue first with TTS-Ultimate.
I'll work on that tomorrow.
Sorry for that!

**Comment by xury77** [comment]
I had the same too.  I fixed it myself, but I don't know is a common solution for other cameras/DVRs
For my DVR  must be sent a frame started
`<VideoOverlay version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<fontSize>1</fontSize>
<TextOverlayList size="6">
<TextOverlay version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<id>1</id>`
This is config for 32x32 size.
Below is my modified hikvisionUltimateText.js:

[hikvisionUltimateText.js.txt](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/5898930/hikvisionUltimateText.js.txt)
So I think the complete must be started at <VideoOverlay....> xml tag.

**Comment by Supergiovane** [comment]
Hi Xuri
nope, this isn't standard, as ISAPI tell to do this in other way.
You suggestion didn't work for neither my NVR nor my cameras.
I'm doing what ISAPI documentation tells to do. Let's see what happens.

**Comment by Supergiovane** [comment]
I've 4 ISAPI documents, and each one is telling a different way to do the same things.
I won't loose other time on that, but i found a solution for all you: i'll create an XML sender node, so you can freely send whatever XML you want.

**Comment by Supergiovane** [comment]
V. 1.0.30 is out with this new node.

**Comment by Deggle** [comment]
Hello,

Shame to not have the functionality in the existing node, but understand the approach - and the benefits when I start to look into ISAPI (not familiar at all yet). Thanks to @xury77 for the code tweak above as that helped get what I was initially doing to work!

Thanks again,

Tim
